### ISSUE TITLE
Sleep and Wake times aren't consistent with Vanilla

### ISSUE THREAD

**Issue by PitchBright** [Abastro/StellarSky#1]
Something about StellarSky (when present on both client and server) makes the player wake up from bed early enough to go jump back into bed and go back to sleep (and skip another whole day).

It also seems as though the mod allows you to go to bed earlier than you can in vanilla minecraft. You can get into bed 2 or 3 minutes early, long before the sun goes down.

**Comment by Abastro** [comment]
Hmm I predicted the problem, but doesn't know that it really happens.
I'll inspect to it. Do you know what the exact version with the problem is?

**Comment by PitchBright** [comment]
V0.1.8

**Comment by Abastro** [comment]
Yes, I'll inspect it in a few days.

**Comment by Abastro** [comment]
Sorry but please post your config settings with it.

**Comment by Abastro** [comment]
Oh Nvm, I found the problem.

**Comment by PitchBright** [comment]
You were correct that the client config was Server Enabled: false, and the server config was Server Enabled: true.

By me setting the client to true, it fixed the wake up time, but I don't think it fixed the sleep time. I was going to do further experiments, with different combinations, let me know if you still need me to or not.

**Comment by PitchBright** [comment]
Okay… with both client and server set to "Server Enabled: True"… the player wakes up at 6:00am (tick 0)… (same as vanilla) so that fixed that problem. But the player can get into bed at 17:50 (around tick 11833) instead of 20:30 (tick 14500) like Vanilla.

**Comment by Abastro** [comment]
Fixed version (v0.1.9) will be out today.

**Comment by Abastro** [comment]
Minecraft Forum didn't allow me to modify the thread..
So first download the 0.1.9 version from here: http://adf.ly/6272560/stellarsky-v019

**Comment by PitchBright** [comment]
Awesome! Thanks.

**Comment by PitchBright** [comment]
Appears to be fixed.
