### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by gamersalpha** [Abastro/StellarSky#100]
Hello, 

i pût this two files in my mods directory, 
![image](https://user-images.githubusercontent.com/32466950/38471103-cc116468-3b6c-11e8-87cc-312ede9f715a.png)

and i have this error : 

do u know what please ?

![image](https://user-images.githubusercontent.com/32466950/38471110-dce7884e-3b6c-11e8-9ecd-69a3af4f5412.png)

**Comment by Abastro** [comment]
Update Stellar Sky... v0.7.5.1.1 is seriously outdated by now.
