### ISSUE TITLE
Completely white sky, no sun/moon/stars, time independant

### ISSUE THREAD

**Issue by TheSpiderDungeon** [Abastro/StellarSky#101]
It's just completely white. I muddled with the settings and I'm not sure what I messed up. CelectialSettings.cfg included so you can yell at me for doing something stupid that should be obvious. I'll try to use the original settings and see if that fixes it.
[CelestialSettings.cfg Inside.zip](https://github.com/Abastro/StellarSky/files/1892582/CelestialSettings.cfg.Inside.zip)

Update: Deleting the cfg and letting the mod remake it fixed the issue, but there's still something in the settings that ruined the skybox. I noticed that the sky just above the horizon is a white gradient to normal blue. Maybe I did something that broke the blue or white part?

**Comment by Abastro** [comment]
Don't know anything about it, I think there's nothing which could cause those issues.
It could be from version change.
As a clean config fike fixed it, I'm going to close it for now.
