### ISSUE TITLE
Moon disappears during the day.

### ISSUE THREAD

**Issue by PitchBright** [Abastro/StellarSky#11]
The light from the sun seems to make the moon disappear during the day. As it gets brighter out during dusk, the moon slowly fades until it disappears.

**Comment by Abastro** [comment]
This is an intended feature.

**Comment by PitchBright** [comment]
Making the moon the disappear during the day, is an intended feature?

**Comment by Abastro** [comment]
Yes. Because moon can rarely be seen on day.

**Comment by PitchBright** [comment]
I'm sorry, but that's not true. The moon is up during the day, 50% of the time.

http://earthsky.org/space/when-can-you-see-a-daytime-moon

And here's a million pictures to prove it:
https://www.google.ca/search?q=picture+of+the+moon+during+the+day&client=safari&rls=en&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiAptfkktDJAhVK6oMKHYmDBhYQ_AUIBygB&biw=1377&bih=902#tbm=isch&q=moon+during+the+day

;)

**Comment by PitchBright** [comment]
If you want to hide things during the day… I would suggest hiding all the planets except Venus (at dusk and dawn). THOSE aren't visible during the day to the naked eye. The TWO things you should be able to see during the day, are the Sun, and the Moon, and that's it.

**Comment by Abastro** [comment]
What I mean by visible was over certain brightness compared with neighborhood.
Maybe our naked eye can see the moon, but it cannot be simulated on optical calculation.
But venus can still be visible. It cannot be seen by naked eye because it is point source unlike moon.

**Comment by PitchBright** [comment]
I was under the impression that you were coding it to make it disappear during the day. Did you code it to make it disappear during the day?

**Comment by Abastro** [comment]
No, What I did was just setting moon not too bright.

**Comment by PitchBright** [comment]
What do you have it's apparent magnitude set to?

**Comment by Abastro** [comment]
Default is the magnitude of the Moon.
