### ISSUE TITLE
Debug info set to ON by default

### ISSUE THREAD

**Issue by PitchBright** [Abastro/StellarSky#12]
Please change the default of the debug info so that it is not set to ON by default, but has to be activated by the user, if they wish to see it.

The debug info interferes with a lot of other mods GUI stuff that is placed in the top-left corner, so it's annoying to have to shut the debug info off every time I play. It should only appear if I want it to. It would be like having to Press F3 to hide Mojang debug info every time you want to play.

**Comment by Abastro** [comment]
Oh I'd change that.

**Comment by PitchBright** [comment]
Awesome, thank you.
