### ISSUE TITLE
Optifine And Stellar Sky Conflict

### ISSUE THREAD

**Issue by enzomtpYT** [Abastro/StellarSky#121]
When installing Stellar Sky With optifine i optain : 
[Client thread/ERROR] [minecraft/Minecraft]: ########## GL ERROR ##########
[Client thread/ERROR] [minecraft/Minecraft]: @ Post render
[Client thread/ERROR] [minecraft/Minecraft]: 1281: Invalid value

Ingame error : OpenGL error : 1281 (Invalid value)

That's spamming the log and i have no more info...

**Comment by jriwanek** [comment]
Please post full logs, not just what you consider relevent.
