### ISSUE TITLE
HUD doesn't work anymore

### ISSUE THREAD

**Issue by PitchBright** [Abastro/StellarSky#17]
After you changed the config file for issue #12 , the new way doesn't work at all. The HUD never comes up, it doesn't matter what I set the config file to.

Issue #12 was not to make the HUD configgable. It was to make it so that when you join the world, the HUD is not shown, by default. The player should press the "P" key, to make the HUD visible.

**Comment by Abastro** [comment]
Yes but i wanted it configurable. Really it doesnt work? Ill look at it.
