### ISSUE TITLE
Sink time between Terrafirmacraft and StellarSky

### ISSUE THREAD

**Issue by dexman545** [Abastro/StellarSky#18]
TFC has years, months, seasons, and days. Would it be possible to sink the two mods time systems together, that way Stellar Sky's time modification will work with TFC's seasons?

**Comment by Abastro** [comment]
For that, some api is needed. Im curious that the terrafirmacraft dev would ever take account for this compatibility.

**Comment by dexman545** [comment]
TFC has an API (https://github.com/Deadrik/TFCraft)...as for them entertaining compatibility....as someone who makes a modpack with TFC I can say the chances of that are low, even lower now that TFC1 is no longer in dev, as they are focusing on TFC2 for 1.8

**Comment by Abastro** [comment]
They dont provide an API for calender, so just impossible.

**Comment by dexman545** [comment]
Yeah...I kind of expected that....thanks for taking the time to look into it.

**Comment by dexman545** [comment]
Would it be possible for Stellar sky to go off of TFC time, instead of the other way around? TFC does provide function to to get time, for instance TFC_Time.getMonth(); in com.bioxx.tfc.Core.TFC_Time

**Comment by Abastro** [comment]
No, it will harm feature of Stellar sky greatly.
