### ISSUE TITLE
Feature Request: Date, Day-length, Wake-time, Sleep-time, Season display info

### ISSUE THREAD

**Issue by PitchBright** [Abastro/StellarSky#2]
Seeing as the StellarSky makes it so that the days get longer and shorter over the course of the year (as configured by:     D:Year_Length=365  …

…it would be extremely informative (critical) for the user to have the option (by config, or menu activation) to display on the screen somewhere (top left or right, small) the following information:

-Current Day & Year Length (ie Day 272/365)  (note: March 20 = Day #1, June 20 = Day #92, September 23 = Day #187, December 22 = Day #277)
-Current Season (ie "Winter")    
-Day Length (in HH:MM format & Ticks)
-Night Length (in HH:MM format & Ticks)
-Wake-up Time (in HH:MM format & Tick #)
-Sleep Time (in HH:MM format & Tick #)

**Comment by Abastro** [comment]
Thanks for the great request! It will be accepted on v0.1.10

**Comment by Abastro** [comment]
Hm what do you mean by 'Wake-up Time' and 'Sleep Time'?

**Comment by PitchBright** [comment]
The time of day (hh:mm) that the player can begin sleeping, and will wake up.

Or are those two values constant throughout the year?

**Comment by Abastro** [comment]
That one would be hard to predict, but I'll try.

**Comment by PitchBright** [comment]
Is Sleep Time and Wake time based on light levels? Or are they hard-coded times like in Vanilla?

**Comment by Abastro** [comment]
Sleep time is based on light levels. Wake time is hardcoded.

**Comment by PitchBright** [comment]
Okay cool. I thought so. In that case, if it will be hard to predict Sleep Time, don't worry about adding a feature to display it. It's not necessary, or critical.

**Comment by Abastro** [comment]
It would be on HUD, and can be enabled/disabled by a key. Is this okay?

**Comment by PitchBright** [comment]
That sounds perfect!

**Comment by Abastro** [comment]
Added in v0.1.13 update.

**Comment by PitchBright** [comment]
The gui "Time" debug info displays the Time based on IRL minutes… but what I was thinking of was Time that displays the in-game "Time of Day"… from 12:00am (Midnight) to 12:00pm (Noon) to 12:00am (Midnight).

For example:

Time: 3:15 pm

**Comment by Abastro** [comment]
So there might be configs for that. (Please reopen this issue)

**Comment by PitchBright** [comment]
I don't think I can re-open it, I think you have to.

What do you mean there might be configs for that?

**Comment by Abastro** [comment]
Something like length of hour and minute.

**Comment by PitchBright** [comment]
Found it. It's in the client's config.

    I:Hour_Length=60
    D:Minute_Length=20

To get a proper DayTime value the, client needs to be set to:

    D:Minute_Length=16.6666


Also, can you change the format so that it has leading zeroes in it? Right now… 06:08 am shows up like 6:8, for example.

It would be much easier to read if it was in the HH:MM format with Leading Zeroes.

**Comment by Abastro** [comment]
Oh I'd fix that. I thought it is shown as 06:08 format.

**Comment by PitchBright** [comment]
Check it out: http://imgur.com/cSpoVmS   Mine doesn't show 6:08… it shows 6:8.

**Comment by PitchBright** [comment]
The GUI is always ON by default when we start Minecraft. Can you make it OFF by default (like the F3 hud), and must be activated by the user using their hotkey?

**Comment by Abastro** [comment]
Ah, I'd also implement those features.

**Comment by Abastro** [comment]
Implemented on v0.1.15.
