### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by PalePyth** [Abastro/StellarSky#21]
http://pastebin.com/pj5afsde

**Comment by Abastro** [comment]
You are using wrong version of SciAPI.
Dependency version is written on curse download link or minecraft forum.

**Comment by PalePyth** [comment]
I use 
Stellar Sky v0.1.15 | **
- v0.1.15 requires SciAPI v0.5.2 to run.
on 1.7.10 as you recommended.
Nevertheless, I created a new world, then tried to load this. Yep, anoher one crash. http://pastebin.com/EWtcuQfE

**Comment by Abastro** [comment]
This is problem of another mod. Maybe streams or farseek mod. Make an ssue there

**Comment by PalePyth** [comment]
Also is there a way to turn off this interface? http://puu.sh/mPciM/e6c7d161b0.jpg I can't find the desired parameter in the configs.

**Comment by Abastro** [comment]
Use latest version.
