### ISSUE TITLE
Suggestion: Configurable lunar cycle

### ISSUE THREAD

**Issue by Sunconure11** [Abastro/StellarSky#26]
Lately I've been noticing in my modpack that the moon is always invisible. I am using Dynamic Surroundings and Hardcore Darkness, if those two mods could be doing this.

**Comment by Abastro** [comment]
Can you give me the screenshot?

**Comment by Sunconure11** [comment]
It might be an issue with Dynamic Surroundings, as removing one or the other stops it, but, I'll take screencaps anyways.

**Comment by Sunconure11** [comment]
I also reported this issue to the dev of the other mod, and I'm going to see if his config changes do anything first.

**Comment by Sunconure11** [comment]
https://github.com/OreCruncher/BetterRain/issues/46

**Comment by Sunconure11** [comment]
His settings didn't work, so, here are screencaps of the world, to the best of my abilities:

https://www.dropbox.com/sh/2q0sw142bye67wd/AADM1HUmbUvezapZG39OCA9Qa?dl=0

**Comment by Sunconure11** [comment]
This appears to be a user error. The moon has finally shown itself. It might be related to the config changes though.

**Comment by Sunconure11** [comment]
However, could you get the moon cycle to be more in sync with vanilla, or at least, have an option to do so? It has some weird issues with other mods (I.E Hardcore Darkness becomes super pitch black during a full moon):

https://www.dropbox.com/s/b68u0dyyqqfysg1/Screenshot%202016-01-30%2010.47.37.png?dl=0

**Comment by Abastro** [comment]
Moon is not always shown.. it is hard to find moon.
And it is problem of the mod using incompatible methods.

**Comment by Sunconure11** [comment]
How would one change the length of the lunar cycle then? I like this mod, but, currently, I need it to be roughly as long as the vanilla one, due to compatibility issues with other mods. Is such a config setting planned?

**Comment by OreCruncher** [comment]
And it is problem of the mod using incompatible methods?

**Comment by Abastro** [comment]
Dont use getCurrentMoonPhaseFactorBody, it is more incompatible. getCurrentMoonPhaseFactor or getMoonPhase is much better.

**Comment by PitchBright** [comment]
@Sunconure11 The moon cycle shouldn't be artificially tied to vanilla like that. The moon orbits the earth IRL, and the earth orbits the sun IRL… and this mod follows that, not mojang. If you want to customize your solar system… I believe that's what Stellarium is for.

**Comment by OreCruncher** [comment]
My mod is calling world.getCurrentMoonPhaseFactor() to get the moons brightness already, so I am not sure what you are seeing/thinking.

**Comment by PitchBright** [comment]
@OreCruncher He might be thinking you're the author for the other mod called Hardcore Darkness, which uses getCurrentMoonPhaseFactorBody()

**Comment by OreCruncher** [comment]
OK - no worries.  Just want to make sure I wasn't doing something boneheaded. :)

**Comment by Abastro** [comment]
Anyway changing lunar cycle cannot be solution for this.
