### ISSUE TITLE
Compatibility with Hardcore Darkness by lumien

### ISSUE THREAD

**Issue by Sunconure11** [Abastro/StellarSky#27]
How do I make this mod work properly with Hardcore Darkness mod? Hardcore Darkness makes it brighter at night when the moon is full, but it doesn't work properly when Stellar Sky is installed, because the moon's phases are different than Vanilla's moon phases.

https://github.com/lumien231/Hardcore-Darkness/issues/13#event-532562240

**Comment by lumien231** [comment]
Would switching from World.getCurrentMoonPhaseFactorBody to World.getCurrentMoonPhaseFactor yield a actually functional method?

**Comment by Abastro** [comment]
@lumien231 It allows more compatibility.

**Comment by Abastro** [comment]
It would fixed on the latest version(v0.1.20).

**Comment by Biochao** [comment]
Just tested this on Stellar Sky version 0.5.5.1.7 and Hardcore Darkness version 1.8 on Minecraft 1.10 and no matter the hardcore darkness mode the night is bright. 
Removing Stellar Sky lets hardcore darkness work in config modes 0 and 2

**Comment by Abastro** [comment]
@Biochao It is impossible for Stellar Sky to support that part.
There is a config optioon in Stellar Sky to control the brightness, it'll be in per-dimension settings.
