### ISSUE TITLE
Star's appear in front of moon

### ISSUE THREAD

**Issue by dexman545** [Abastro/StellarSky#29]
Best way to convey this is a picture, so: https://imgur.com/a/aaF5S
Config for stellar sky, in case it is needed: http://pastebin.com/JYeXWyzr

**Comment by PitchBright** [comment]
We're aware of this one. It's something I was planning to address soon.

Thanks @dexman545 ! :-)

**Comment by Abastro** [comment]
This is something i cannot fix, because atmosphere is drawn first before objects.

**Comment by PitchBright** [comment]
Abastro, I've already started thinking this one through, I believe I have the solution.

**Comment by PitchBright** [comment]
@dexman545 Another issue that you may not be aware of, is that when you make your moon size that big, it's brightness needs to be pushed up a bit too. Unfortunately, the Moon's Halo doesn't scale up with the size of the moon. That's why you can't see it, at the moment.

I've dabbled with trying to fix this, but it was lower priority, so I didn't solve it yet.

**Comment by Abastro** [comment]
Its nearly impossible before rendering atmosphere from my end. Because moon should be blended with the sky, and shade stars.

**Comment by dexman545** [comment]
Ahh,ok, thanks. @PitchBright, thanks for tip on the brightness part! 

ON a side note, is there any particular reason why the config for the fragments of the moon are so far way from the rest of the config dealing with the moon? It might just be me, but it feels a little awkward.

**Comment by PitchBright** [comment]
@dexman545 No particular reason. Things got added to the config, bit by bit, and it didn't get re-organized.

**Comment by PitchBright** [comment]
Looking more closely at it… I see that Moon Fragments is a client-side configurable… where as Moon Size and Brightness are server-side. That's probably why they are in different sections.

Users can change the level of detail they see in the moon, via Moon Fragments.. but the server should always control how big the moon is, and how bright it is.

**Comment by Abastro** [comment]
@dexman545 Its because it is clientside configuration which you can modify for fps. But server configs for moon is what you should not differ.
And the config does got aligned, classified by cosmetics & fps part, and feature part.

**Comment by dexman545** [comment]
Ahh, ok then. Just curious.

**Comment by Abastro** [comment]
Fixed it.
