### ISSUE TITLE
WorldTime Offset

### ISSUE THREAD

**Issue by PitchBright** [Abastro/StellarSky#3]
It would be really handy we were able to have an Offset for the World Time in the config. My understanding of the way StellarSky works is that it shows you the night sky based on the World Time… advanced from Real Life "Time 0".

If somebody wants to run a minecraft server "in real time"… relative to the real world… they would need an offset to manually adjust their World Time.

For example… I like to have each IRL Week, be 1/4 of a Stellar Sky year. My Stellar Sky year is 880 Minecraft Days. The first week of the month I would like to be Spring. I believe Stellar Sky uses a specific date as "Day 1" (or "Time 0")… I forget if you said it was it was January 1, 4713 BC 12:00pm Noon GMT… or something like that… but it's based on a hardcoded date. I would require an offset to adjust how the mod reads my world's "worldtime" in order to align my Minecraft world, with the Real World, in a way that I would like it to.

Also… it would be a good idea to put somewhere in the config file a commented out line that states what the hardcoded Day 1 ("Time 0") is… just for those that would also like the reference.

**Comment by Abastro** [comment]
Thanks for the great request! It will be accepted on v0.1.10

**Comment by Abastro** [comment]
Added in v0.1.13[1.7.10].

**Comment by PitchBright** [comment]
What is the hardcoded default zero date in the mod?

How do I use the new offset times in the configs? (what do the mean?)

**Comment by Abastro** [comment]
Offset time is just the starting time.
IDK what was default zero date IRL.

**Comment by PitchBright** [comment]
Oh I found it, when we were talking about it back in March earlier this year.

On 2015-03-15, at 8:28 PM, Abastro (Stellar Sky coder) wrote:
> So I found that it starts on 5000 tick after Julian date 0

On 2015-03-15, at 8:29 PM, Abastro (Stellar Sky coder) wrote:
> 12h January 1, 4713 BC

Looks like it's  12:00:00 (PM - Noon) January 1, 4713 BC, and then you've added the option for us to use the default Tick Offset of 5000, or customize it ourselves.

But when I "/time set 0", it definitely turns night though, not Noon…. or 5000 ticks after Noon.

You also mentioned that you've set Precession to 0, so I think it doesn't really matter what the year is then (unless you've placed the Moon and Planets in different positions that what they were on Jan 1, 4713 BC).

Is that the date you set the Moon and Planets to? I'm just curious, it's not super important.

**Comment by Abastro** [comment]
Yes it is the date I set on the moon and planets too.

**Comment by PitchBright** [comment]
The strange thing is when I was testing last night, looking east, /time set 0... The sun rises in the east at the spot where it would rise on June 21, not January 1. 

(I have to do more testing, but maybe I'll make a video or screenshare with you on skype and show you. Plus I found a really cool tool on the web you will really like.)

**Comment by Abastro** [comment]
If it were Julian date 0, It would be 12:00:00 (AM - Noon) January 1, 4713 BC.
So it would be something another.

**Comment by PitchBright** [comment]
Noon = PM

I'll show ya when I wake.
