### ISSUE TITLE
[Suggestion] Prevent Stellarsky 0.1.19+ from loading MC with outdated SciAPI

### ISSUE THREAD

**Issue by dexman545** [Abastro/StellarSky#30]
Minecraft will load, without issue, when StellarSky 0.1.19 and SciAPI 0.5 are present(I don't know which version this started happening in, but it definatley continues). The problem with this is that SciAPI seems to be missing something, so when a world is loaded, players are met with a huge like spike (huge as in normal 60 FPS becomes a constant 0-1 FPS). Not really an issue for those who remember to check for updates from dependencies, but it can be annoying. Other mods with dependencies will prevent MC from reaching the title screen, and give the player notification of the outdated API. Is this something that could be done for Stellar Sky?

**Comment by Abastro** [comment]
Really thank you for catching that part. It would be fixed on next version.

**Comment by dexman545** [comment]
Cool, thanks :). Not going to lie...I kinda put off updating Stellar Sky for a while because of this (many mods in  modpack=harder to keep track of updates :P).

**Comment by Abastro** [comment]
Fixed on v0.1.20.
