### ISSUE TITLE
Update to latest available build of Calendar API

### ISSUE THREAD

**Issue by Sunconure11** [Abastro/StellarSky#31]
Version 1.04 is the version on Curseforge, and you should update this mod to that version, as not everyone will use the jenkins link.

**Comment by Abastro** [comment]
Calendar api support is not yet implemented.

**Comment by Sunconure11** [comment]
I know. but, you have it coded as an optional dependency.

**Comment by Sunconure11** [comment]
https://github.com/Abastro/StellarSky/commit/a7b5031fd0e13f21d360da36e434ca28fad12f53

**Comment by Abastro** [comment]
Yes. It will be fixed to the appropriate version when calendar api compatibility is ready.

**Comment by Sunconure11** [comment]
Alright
