### ISSUE TITLE
Performance hotspot in ExtinctionRefraction.Refraction

### ISSUE THREAD

**Issue by codewarrior0** [Abastro/StellarSky#32]
Stellar Sky-v0.1.15[1.7.10]

Started up TechnoFirmaCraft for the first time and saw my FPS in the 10-12 range. A snapshot with the VisualVM sampler fingered some of your code. Let me know if you need any more info.

![image](https://cloud.githubusercontent.com/assets/307683/13028312/4d7c955a-d20f-11e5-997f-a508176e1403.png)

**Comment by Abastro** [comment]
Thank you for letting me know the fact!
But it is hard to overcome, i might try caching.

**Comment by PitchBright** [comment]
Stellar Sky-v0.1.15[1.7.10]

Super old version  ^^^

**Comment by PitchBright** [comment]
@codewarrior0 What do you mean "TechnoFirmaCraft"?

**Comment by PitchBright** [comment]
@codewarrior0 also, can you post your StellarSky config file please?

Thanks!

**Comment by Abastro** [comment]
@PitchBright indeed the version is old, but this can still give a hint that what part causes lag on stellar sky.

**Comment by PitchBright** [comment]
Cool. It'll help too if we knew what his settings are.

**Comment by Abastro** [comment]
Yes. But not neccessary.

**Comment by codewarrior0** [comment]
[Technofirma](http://forum.feed-the-beast.com/threads/1-7-10-technofirma-the-original-terrafirmacraft-modpack.49502/) is a hardcore questing modpack. Seems like it hasn't been updated in a while.

Because of the modpack, I don't know if I'm using a stock config. [My config file.](https://gist.github.com/codewarrior0/5b059978916d45277c5d) Changing the first option `Mag_Limit` all the way down to 0.3 did help, but then there are almost no stars.

I updated to Stellar Sky-v0.1.20[1.7.10] and saw pretty much the same thing, though it isn't quite as bad:

![image](https://cloud.githubusercontent.com/assets/307683/13028630/81e9a112-d218-11e5-9367-5e22c13604ec.png)

**Comment by Abastro** [comment]
@codewarrior0 The mag limit config means that you can decrease it by 0.3 (not to 0.3) to reduce lag.

**Comment by PitchBright** [comment]
@codewarrior0 thanks for putting up the infos.

**Comment by Abastro** [comment]
Fixed this. (See 1.7.10 and 1.8)
Thank you!
