### ISSUE TITLE
StellarSky conflict with Optifine displays minecraft clock incorrectly

### ISSUE THREAD

**Issue by PitchBright** [Abastro/StellarSky#4]
When SciAPI & StellarSky are on the server… clients would connect, and their minecraft clock weren't working (the animation always showed "noon").

The temporary fix is to go into video settings, turn animations off… disconnect from the server… turn them back on in the main menu, and then reconnect to the server.

The problem doesn't return, until the client quits minecraft and starts it up again. If they don't quit MC, then the problem won't return and they are able to see the correct time, even if they relog on the server.

The problem dates back to last March, but then it disappeared after I did an update to my server this summer. Since updating again, the problem has resurfaced. (Outside chance that it was broken in Forge 1230, fixed in Forge 1291, and then it broke again in Forge 1448…. but I can't remember for sure if those updates coincide with the problem.)

The problem doesn't occur if I remove Optifine, and leave Stellar Sky in.
The problem also doesn't occur if I remove Stellar Sky, and leave Optifine in.

**Comment by Abastro** [comment]
I think it is incompatibility between Stellar Sky and Optifine,
But I will investigate this issue.

**Comment by Abastro** [comment]
I really cannot know what is happening in this issue,
But I expect that Optifine might use alternative TextureClock instance.
Which version of Optifine do you use?

**Comment by PitchBright** [comment]
OptiFine_1.7.10_HD_C1

and I've tried the previous 3 versions of each of the Ultra and Standard editions as well. (Lite edition doesn't work with Forge.)

**Comment by Abastro** [comment]
Sorry, I couldn't find how to put optifine as a mod in dev environment.
So I couldn't guarantee compatibility with optifine, like many other mods.

**Comment by PitchBright** [comment]
It appears you have fixed the problem in the latest update.

**Comment by PitchBright** [comment]
Maybe not fixed. I just experienced it again, for some reason. Will test further.

**Comment by Abastro** [comment]
Is it fixed? If not, please let me know when this bug appears.

**Comment by PitchBright** [comment]
I'm still narrowing the problem down to something to do with optifine (and it's possibly part of the McPatcher code included in OF). I'll keep you posted, as I get closer to the solution. I've been digging deep into McPatcher the last few days. It could be related to some sort of item/animation feature in there. Still not 100% sure yet.

**Comment by PitchBright** [comment]
I can now confirm it's definitely not McPatcher related. More testing to come.

**Comment by PitchBright** [comment]
Closing this, as it's related to Optfine, and Server-resourcepack (possibly /assets/minecraft/textures/environment/clouds.png) related.
