### ISSUE TITLE
Possible crash with this mod and modded dimensions

### ISSUE THREAD

**Issue by Sunconure11** [Abastro/StellarSky#40]
http://pastebin.com/qJSSzjqG

Player encountered this on my server, there is a good chance it is related to this mod.

**Comment by Abastro** [comment]
Where did it happened? On server, or client?

**Comment by Sunconure11** [comment]
Server.

**Comment by Abastro** [comment]
Oh it should be client because there is Minecraft.class

**Comment by Abastro** [comment]
Oh, does it happened from dedicated server side? It seems impossible.

**Comment by Sunconure11** [comment]
It happened on a dedicated server, the player attempted to use the erebus dimension, and after I tried to deal with a ticking entity error, this error appeared.

The server is using KCauldron, as there aren't enough Forge mods to allow for all of the functions bukkit plugin allow.

**Comment by PitchBright** [comment]
Is the crash report from the client, or from the server?... I think is what he's asking.

**Comment by Sunconure11** [comment]
Only this player crashes, so, clientside.

**Comment by PitchBright** [comment]
The player gave you that crash report?

**Comment by Abastro** [comment]
Okay, id fix it till tomorrow.

**Comment by Sunconure11** [comment]
Yes, the player gave me the crash report.

**Comment by Abastro** [comment]
Fixed on commit: 19ee0253851cafb646d8c5d8bbe5540c5ac755ab

**Comment by Sunconure11** [comment]
I think your solution might be trying to load something on an invalid end of the mod:

http://pastebin.com/gV00aVur

**Comment by Abastro** [comment]
Fixed on efc14808be317cb42216259671688f3c42705ead.
