### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by mellexpro** [Abastro/StellarSky#41]
Game crashes while making new map, using FTB-Infinity and realistic Terrain Generation.

When Removing Stellar Sky, Map works as expected. Stellar Sky Version: 0.1.25b[1.7.10]

[crash-2016-03-19_16.14.33-client.txt](https://github.com/Abastro/StellarSky/files/180846/crash-2016-03-19_16.14.33-client.txt)
[fml-client-latest.txt](https://github.com/Abastro/StellarSky/files/180847/fml-client-latest.txt)
[latest.txt](https://github.com/Abastro/StellarSky/files/180848/latest.txt)

**Comment by Abastro** [comment]
Id look at it.
Does it crashes before client starts?

**Comment by mellexpro** [comment]
If I am understanding you correctly, yes the client window is open and I am busy creating a new map when the crash occurs
Create New World ---> Building Terrain ---> Downloading World ---> Freeze ---> Shutting Down Internal Server ---> Crash Back To Launcher

**Comment by Abastro** [comment]
Compatiblity with funky lcomotion, which is very hard to fix..

**Comment by mellexpro** [comment]
Hi Abastro. Can you elaborate a bit more on what the compatibility issue is, i would like to address this issue with the author of funky locomotion as well.

**Comment by Abastro** [comment]
Fake World calling WorldEvent.Load
