### ISSUE TITLE
Enemy Mobs not Lit On Fire During the Day (1.8.9)

### ISSUE THREAD

**Issue by Zetal911** [Abastro/StellarSky#42]
Like the title suggests, mobs are lit on fire very late in the day, such that the sun has already risen for quite some time.

This makes it sort've awkward since mobs will, often times, spawn in the morning right when a world has just been generated before the player even has any weapons. In worst case scenario's, several zombies can aggro right when the world is created.

**Comment by Abastro** [comment]
1. Fixed on 1.9,
2. Will be fixed on next version of 1.8.9

**Comment by Abastro** [comment]
Fixed on 4ddb1d869e1373630fbdcca8588f85c6a8e51c1f.
