### ISSUE TITLE
Custom_Wake_Enabled=true Breaks Bed Sleeping Animation (1.8.9)

### ISSUE THREAD

**Issue by Zetal911** [Abastro/StellarSky#43]
Sleeping works fine, functionally, but when the player sleeps in the bed their character is not moved to be in the bed, and it will seem like they aren't in the bed at all. After a few seconds, it will become day, and their position gets set to where they would have gotten out of bed.

**Comment by Abastro** [comment]
It will be fixed on the next version.

**Comment by Abastro** [comment]
Fixed on commit 4ddb1d869e1373630fbdcca8588f85c6a8e51c1f.
