### ISSUE TITLE
stellar-sky-1.9-0.3.1.1 crashes dedicated forge server 1.9 build 1811 on startup

### ISSUE THREAD

**Issue by kreezxil** [Abastro/StellarSky#44]
I had disabled this yesterday when SCI api blew a gasket, and reactivated today when the sciapi update came out. So now Stellar Sky itself is crashing the server. 

Issue: stellar-sky-1.9-0.3.1.1 crashes dedicated forge server 1.9 build 1811 on startup

crash report:
https://gist.github.com/e50c8372050528eeea1a

fml server latest:
https://gist.github.com/92553de6242fde7276d1

**Comment by Abastro** [comment]
Note that this update contains too many changes. (It is actually like 'another forge version'),
So no forward/backward-compatible can be guaranteed.
