### ISSUE TITLE
Feature Request: Non SS-Server Sun Path

### ISSUE THREAD

**Issue by PitchBright** [Abastro/StellarSky#45]
Putting this here as a reminder about our conversation:

If the client has SS installed, and the client goes on to a server that does NOT have SS installed… the client's Sun position will not match the server's Sun position. This sometimes causes confusion for players, and they think it's daytime, when in fact it is still night (according to the server).

An example of this would be 5am on a Summer morning. The sun is "up" and it is daytime at 5am on a Summer morning, on the client. The player sees that it is "day". Because the server does not have SS installed, 5am is still "night" and it is dark… and mobs will spawn and not burn. The client will see the mobs and wonder why they are spawning during "the day".

It would be a good feature to make it so that if a client goes on a server that does not have SS installed… the client automatically switches to a mode where the Sun follows the Right Ascension line, travelling from due East to due West… just like Vanilla.

You could also add a configurable option for the server config if server admins want the sun to follow the Vanilla path. It should be "false" by default, though.

```
serverconfig {
    # Enables Server-Side Sky change.
    B:Server_Enabled=true
    B:Vanilla_Sun_Path=false
```

**Comment by Abastro** [comment]
Implemented this on 7249a37a1de072f2d46ce55849ecea388397a4b9,
When Server_Enabled is false or the server does not have Stellar Sky installed,
The axial tilt is forced to be 0.
