### ISSUE TITLE
Stellar Sky-0.3.1.2 crashes client when you drag resize the client screen

### ISSUE THREAD

**Issue by kreezxil** [Abastro/StellarSky#46]
fml log: http://paste.ee/p/ZLjEe
crash report: http://paste.ee/p/t7Dr4

**Comment by Abastro** [comment]
Where did it happened, on what dimension?

**Comment by Abastro** [comment]
Fixed on dfb384dda3a477a264e625ef85b12bc4992918c8.

**Comment by kreezxil** [comment]
Overworld. However I didn't even log on to the server or start a world.

-----Original Message-----

**Comment by Abastro** [comment]
Yes, this issue had fixed.
