### ISSUE TITLE
Black box below player when Y<61 in void worlds

### ISSUE THREAD

**Issue by Nagapito** [Abastro/StellarSky#47]
This is not really a bug from the mod but minecraft draws this horrendus and strange box at player feet when player is below level 61-62.Blocks are always draw over it so on a normal world its not noticed but on a sky block world, it just makes it look horrible.

I noticed Vazkii's Garden of Glass does not have this issue so, it might be possible to override it?

here is an example of what happens: http://imgur.com/pBpHhxO

PS: this is in 1.7.10

**Comment by Abastro** [comment]
What version of stellar sky are you using?

**Comment by Nagapito** [comment]
Ups. Sorry, forgot to mention that.

Both mods at the latest version.

Stellar Sky v0.1.29
SciAPI v1.1.0.0

**Comment by Abastro** [comment]
Can't find this issue on empty world in current version, so assume that it has been fixed.

**Comment by Nagapito** [comment]
I dont understand this.... 

Yes, you are right it doesnt happen on a normal world. Even on a flat 1 height, I can break the bottom blocks and it doesnt happen. Seems to only happen with YUNoMakeGoodMap mod from LexManos... 

I will bring this issue to him then

**Comment by Nagapito** [comment]
I love you!
