### ISSUE TITLE
Add option to change the location of the sky settings lock

### ISSUE THREAD

**Issue by Sunconure11** [Abastro/StellarSky#48]
https://www.dropbox.com/s/azq5467jbfiw3nq/Screenshot%202016-04-04%2020.17.44.png?dl=0

Uh...

**Comment by Abastro** [comment]
Fixed on commit 023524362d991e494b9a6e25a64b147df3c1bc1a. It will be released in an hour.

**Comment by Sunconure11** [comment]
It does not appear to be working, every time I change the setting to bottomleft, like the config says, it just resets it self back.
