### ISSUE TITLE
Ender Dragon respawns automatically [1.9]

### ISSUE THREAD

**Issue by spacerecycler** [Abastro/StellarSky#49]
There's an odd issue that came up in a modpack I've been helping to test for 1.9.  When I have SciAPI and Stellar Sky installed, the Ender Dragon's health does not update and respawns after a certain amount of time when killed.  It also doesn't spawn a the End portal blocks or the Ender Dragon eggs.

Environment:
MC 1.9
Forge 12.16.0.1811
SciAPI 1.3.0.3
Stellar Sky 0.3.2.2 and 0.3.1.3

Steps to repro:
Create new world and go into creative
Create an end portal and go to the end
Kill the Ender Dragon

I was using this command `/give @p minecraft:diamond_sword 1 0 {ench:[{id:16,lvl:2000}]}` to give myself a sharpness 2000 sword to kill the Ender Dragon in one hit to test this.  I think Forge/MCP is still in flux so I'm guessing you might not get to this immediately but since I saw it still existed in the latest release I thought it was worth filing.  I've only tested two versions of Stellar Sky, the one in the pack and the latest release.

**Comment by Abastro** [comment]
How did you created end portal? Did you find just an existing one, or did you create a new one?

**Comment by spacerecycler** [comment]
I just created a new end portal by using the frames you can place from creative.  Hopefully that doesn't cause any side effects but that was how I was testing it.

**Comment by Abastro** [comment]
Since im not ne able to create one.. please demonstrate your setup.

**Comment by spacerecycler** [comment]
Sorry I misunderstood.  The directionality of the end frames does matter and they all have to be facing inwards to create the portal.  I typically would place them from a single point, right in the middle of the portal I'm creating.  Here's an imgur album http://imgur.com/a/CikzJ.  Through the course of documenting this I think there might even be an easier way than creating a portal.  You can use `/setblock ~ ~ ~ minecraft:end_portal` to set the block you are in to an end portal.  It won't be a proper 3x3 but it still works.  I would still recommend going into creative though.

**Comment by spacerecycler** [comment]
Thanks tested and it works great :)
