### ISSUE TITLE
Moon is fuzzy.

### ISSUE THREAD

**Issue by PitchBright** [Abastro/StellarSky#5]
Is it possible to disable the glow around the moon during the day, but keep the glow for night? It looks like a second sun, and people think the server is messing up with 2 suns.

If not, is it possible to remove the glow altogether? It would be better to not have it at all I think, than to have it look like a second sun.

**Comment by Abastro** [comment]
I should've fix it.. I'll remove it on daytime in the next version. on 1.7.10

**Comment by PitchBright** [comment]
That's awesome, thanks!

**Comment by Abastro** [comment]
Fixed it on Stellar Sky v0.1.12
Test it if it is appropriate or not.

**Comment by PitchBright** [comment]
The visibility of the Moon is much much better, thank you! 

The moon does feel a little bit small though, is it easy for you to increase it's size? It should be the same size as the Sun.

**Comment by Abastro** [comment]
Please make another suggestion for that.
