### ISSUE TITLE
custom sky suggestion

### ISSUE THREAD

**Issue by superon** [Abastro/StellarSky#50]
thinking it would be great to have an option for "custom sky" for use in alternate "dimensions":
     custom milkyway .png
     maybe custom planets and custom satellites too?

**Comment by Abastro** [comment]
Custom textures per dimension? Cool, it would be added on the next version.
But custom planets feature would take time to be added since it is very tricky.

**Comment by superon** [comment]
i figure the planets would be a pain, i had the mag limit set to 0.1 (because setting it the zero made the milky way disappear too, although planets are still visible) and milky way brightness set to 2, also noticed the client-side "contrast" option which really helps making the transition between night and day smoother.   noting that the milky way looks to be and image which spans the whole sky other stars and planets have their positions calculated separately.   adding a "custom sky" option (similar to the milky way overlay) would make a great difference to anyone that has mystcraft or any alt-dimension creating mods.

**Comment by Abastro** [comment]
You mean that sky overlay which can be also seen on day would be good?

**Comment by superon** [comment]
well, when you put it like that, how could it not be awesome?:)

**Comment by Abastro** [comment]
Dimension-dependent textures are added as features on the latest versions.
Please reopen this issue if you have additional suggestions related with sky texture customization.

**Comment by superon** [comment]
cooolbeans, well since you ask, i'm thinking a static horizon layer would also be really neat, the idea is to add distant mountains or such, and possibly do something about the sky visible through the ocean (unless that's actually fixed by the "B:Hide_Objects_Under_Horizon=true"... it does appear to be);)

**Comment by Sunconure11** [comment]
There is a setting to change the moon size, but if you want lunar cycles to end up being changed as a result of it being closer or further, that is currently not in this mod as far as I am aware. Look for any settings dealing with moon size, and toy around with them.

**Comment by superon** [comment]
ahh, yes, i thought there was but couldn't find it in-game, upon rechecking i see it's in the server "common" section;) thanks

**Comment by superon** [comment]
my inability to find the option to resize the moon aside, the aesthetics would still benefit greatly as i imagine it if the moon was flattened.  as it is it looks like you're using a sphere to raycast for phases.
also the horizon suggestion is still a solid idea;)

**Comment by Abastro** [comment]
@superon No, moon is sphere in real, so it should be rendered as sphere. I'd not follow vanilla mechanics there.

**Comment by superon** [comment]
yes, the moon is a sphere (roughly speaking), this is no reason to render it as such though:/
if you really want it spherical you could try using a smooth/interpolated mesh?

even so, a more accurate analogue can be created with a flat image using the vanilla mechanics than using an image mapped onto the surface of a "sphere", not so many calculations required here.
also adding things like "blue moons" could be made additional much easier.

i think unless you're intending to add heavenly bodies that reflect off the surface of the moon (super bright UFOs, or super-close supernova perhaps) or being able to travel/move around it (to view it from other angles) i fail to see how modelling a spherical moon isn't just making things more difficult for yourself and the computer handling the graphics, sorry.

either way, we may still disagree here.  
what are your thoughts about the added horizon layer?

**Comment by Abastro** [comment]
No.. blue moon is not easy even with flat image. The problem was totally not about rendering.
Also I already applied smooth/interpolated mesh, the effect you saying might from refractions. there would be viewpoint planet settings too.

Anyway. I am positive with horizon layer. Maybe with next update?

**Comment by superon** [comment]
ahhh cool, does that mean one of your other mods which lets one view the moon as if from a different planet?
if so then that is nifty indeed;)
or was that just meaning getting a corrected rotation depending on Earthly latitude?

happy to read you're considering the horizon layer.
i feel i should add another suggestion so how about adding animation to halos via tweening images, fading transparency and/or revolving the single image?

**Comment by superon** [comment]
also maybe a few cloud layers (all sorts of different clouds that may appear randomly or set by weather), sounds simple though probably not.

**Comment by Abastro** [comment]
Cloud layers are very difficult, and there are already a mod controlling that part. So I'll not work on it.

**Comment by PitchBright** [comment]
@superon What makes you think the moon is 3D?

https://github.com/Abastro/StellarSky/blob/1.7-v0.1.25/src/main/java/stellarium/render/CelestialLayerMoon.java#L116

**Comment by superon** [comment]
hey hi PitchBright, now you should know better than to think i know how to understand that code enough to relate meaning;)  thanks for posting it though, always an interesting read...   i initially thought it's 3D because of the appearance of the texture used:
![lune](https://cloud.githubusercontent.com/assets/5957924/14524952/07ac3f36-0233-11e6-99dd-231adfa001f5.png)
