### ISSUE TITLE
Stellar Sky is attempting to run something on the wrong end, part 2: electric boogaloo

### ISSUE THREAD

**Issue by Sunconure11** [Abastro/StellarSky#51]
http://pastebin.com/tFQPYhiw

This error popped up once, then it appears to have stopped. I'll investigate a bit more.

**Comment by Abastro** [comment]
Stellar Sky v0.1.25 is alpha version, do not use that.

**Comment by Sunconure11** [comment]
Uh, its the latest from curse, its the build with the fixed config settings and such, you just screwed up naming. Heavily.

https://www.dropbox.com/s/t4nwm0tzajey2rf/Screenshot%202016-04-09%2013.08.27.png?dl=0

**Comment by Abastro** [comment]
Unbelievable. The message says that it is v0.1.25, and the mod which is installed is Stellar Sky-v0.1.25[1.7.10].jar.
Might be bug with curse.

**Comment by Sunconure11** [comment]
It's a user error. I accidentally sent you an old log, and thought the server crashed.
