### ISSUE TITLE
crash entering new dim using SimpleDimensions

### ISSUE THREAD

**Issue by superon** [Abastro/StellarSky#52]
have just updated to SD version 1.3 and now receive this crash from the client:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  Java8CheckerCoremod (Pixelmon-1.8.9-4.2.3-universal.jar)
  FMLPlugin (InventoryTweaks-1.60-dev-27.jar)
  LoadingPlugin (HardcoreDarkness-MC1.8.8-1.8.jar)
  NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 10/04/16 14:04
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at stellarium.stellars.system.MoonRenderCache.updateCache(MoonRenderCache.java:42)
	at stellarium.stellars.system.MoonRenderCache.updateCache(MoonRenderCache.java:14)
	at stellarium.stellars.layer.CelestialManager.updateClient(CelestialManager.java:89)
	at stellarium.stellars.StellarManager.updateClient(StellarManager.java:123)
	at stellarium.StellarTickHandler.tickStart(StellarTickHandler.java:44)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_188_StellarTickHandler_tickStart_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:331)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1624)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at stellarium.stellars.system.MoonRenderCache.updateCache(MoonRenderCache.java:42)
	at stellarium.stellars.system.MoonRenderCache.updateCache(MoonRenderCache.java:14)
	at stellarium.stellars.layer.CelestialManager.updateClient(CelestialManager.java:89)
	at stellarium.stellars.StellarManager.updateClient(StellarManager.java:123)
	at stellarium.StellarTickHandler.tickStart(StellarTickHandler.java:44)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_188_StellarTickHandler_tickStart_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:331)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['stuperon'/135, l='MpServer', x=493.00, y=12.00, z=272.00]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: 454.00,65.00,129.00 - World: (454,65,129), Chunk: (at 6,4,1 in 28,8; contains blocks 448,0,128 to 463,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3608 game time, 3608 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 88 total; [EntityTaintacle['Taintacle'/640, l='MpServer', x=550.50, y=71.00, z=307.50], EntityTaintacle['Taintacle'/641, l='MpServer', x=461.50, y=64.00, z=252.50], EntityPlayerSP['stuperon'/135, l='MpServer', x=493.00, y=12.00, z=272.00], EntityAuraNode['Aura Node'/3, l='MpServer', x=367.50, y=63.50, z=194.50], EntityAuraNode['Aura Node'/4, l='MpServer', x=365.50, y=68.50, z=230.50], EntityTaintacle['Taintacle'/1029, l='MpServer', x=522.50, y=90.00, z=244.50], EntityAuraNode['Aura Node'/6, l='MpServer', x=376.50, y=63.50, z=255.50], EntityAuraNode['Aura Node'/7, l='MpServer', x=392.50, y=64.50, z=227.50], EntityTaintacle['Taintacle'/136, l='MpServer', x=485.50, y=74.00, z=272.50], EntityAuraNode['Aura Node'/8, l='MpServer', x=404.50, y=63.50, z=223.50], EntityTaintacle['Taintacle'/139, l='MpServer', x=485.50, y=77.00, z=263.50], EntityTaintacle['Taintacle'/140, l='MpServer', x=465.50, y=40.00, z=290.50], EntityTaintacle['Taintacle'/780, l='MpServer', x=506.50, y=76.00, z=268.50], EntityAuraNode['Aura Node'/142, l='MpServer', x=474.50, y=65.50, z=267.50], EntityTaintacle['Taintacle'/144, l='MpServer', x=500.50, y=69.00, z=256.50], EntityTaintacle['Taintacle'/145, l='MpServer', x=505.50, y=73.00, z=303.50], EntityTaintacle['Warped Taintacle'/148, l='MpServer', x=493.50, y=73.00, z=316.50], EntityTaintacle['Taintacle'/660, l='MpServer', x=511.50, y=68.00, z=300.50], EntityTaintacle['Taintacle'/149, l='MpServer', x=469.50, y=72.00, z=310.50], EntityTaintacle['Taintacle'/661, l='MpServer', x=553.50, y=75.00, z=273.50], EntityTaintacle['Taintacle'/150, l='MpServer', x=461.50, y=67.00, z=266.50], EntityTaintacle['Taintacle'/22, l='MpServer', x=457.50, y=64.00, z=240.50], EntityTaintacle['Taintacle'/1046, l='MpServer', x=536.50, y=83.00, z=238.50], EntityTaintacle['Taintacle'/152, l='MpServer', x=526.50, y=76.00, z=271.50], EntityTaintacle['Undying Taintacle'/154, l='MpServer', x=511.50, y=71.00, z=314.50], EntityTaintacle['Taintacle'/155, l='MpServer', x=452.50, y=71.00, z=316.50], EntityTaintacle['Taintacle'/539, l='MpServer', x=521.50, y=76.00, z=264.50], EntityTaintacle['Taintacle'/667, l='MpServer', x=488.50, y=64.00, z=310.50], EntityTaintacle['Taintacle'/923, l='MpServer', x=522.50, y=87.00, z=214.50], EntityTaintacle['Taintacle'/157, l='MpServer', x=542.50, y=78.00, z=276.50], EntityTaintacle['Taintacle'/164, l='MpServer', x=443.50, y=75.00, z=303.50], EntityAuraNode['Aura Node'/166, l='MpServer', x=447.50, y=87.50, z=259.50], EntityTaintacle['Taintacle'/551, l='MpServer', x=454.50, y=74.00, z=304.50], EntityTaintacle['Taintacle'/169, l='MpServer', x=542.50, y=81.00, z=261.50], EntityTaintacle['Taintacle'/41, l='MpServer', x=488.50, y=65.00, z=246.50], EntityTaintacle['Taintacle'/939, l='MpServer', x=502.50, y=72.00, z=282.50], EntityPixelmon['Magikarp'/1068, l='MpServer', x=482.52, y=62.00, z=293.81], EntityTaintacle['Taintacle'/173, l='MpServer', x=534.50, y=71.00, z=316.50], EntityPixelmon['Magikarp'/1069, l='MpServer', x=483.04, y=62.00, z=295.69], EntityPixelmon['Murkrow'/1070, l='MpServer', x=517.50, y=74.00, z=251.50], EntityTaintacle['Taintacle'/175, l='MpServer', x=548.50, y=75.00, z=282.50], EntityTaintacle['Taintacle'/687, l='MpServer', x=516.50, y=82.00, z=232.50], EntityItemFrame['entity.ItemFrame.name'/48, l='MpServer', x=502.50, y=67.50, z=155.97], EntityTaintacle['Taintacle'/944, l='MpServer', x=522.50, y=89.00, z=229.50], EntityTaintacle['Sickly Taintacle'/177, l='MpServer', x=548.50, y=88.00, z=256.50], EntityAuraNode['Aura Node'/178, l='MpServer', x=436.50, y=70.50, z=333.50], EntityTaintacle['Taintacle'/180, l='MpServer', x=540.50, y=72.00, z=328.50], EntityAuraNode['Aura Node'/185, l='MpServer', x=489.50, y=89.50, z=405.50], EntityAuraNode['Aura Node'/186, l='MpServer', x=621.50, y=73.50, z=300.50], EntityTaintacle['Taintacle'/443, l='MpServer', x=497.50, y=78.00, z=227.50], EntityAuraNode['Aura Node'/188, l='MpServer', x=606.50, y=66.50, z=412.50], EntityTaintacle['Taintacle'/700, l='MpServer', x=494.50, y=66.00, z=240.50], EntityTaintacle['Taintacle'/701, l='MpServer', x=502.50, y=70.00, z=266.50], EntityPixelmon['Golbat'/194, l='MpServer', x=513.75, y=76.50, z=243.25], EntityAuraNode['Aura Node'/67, l='MpServer', x=541.50, y=71.50, z=196.50], EntityPixelmon['Slowpoke'/196, l='MpServer', x=446.13, y=64.00, z=262.56], EntityTaintacle['Taintacle'/324, l='MpServer', x=483.50, y=64.00, z=253.50], EntityTaintacle['Taintacle'/71, l='MpServer', x=538.50, y=91.00, z=238.50], EntityTaintacle['Taintacle'/839, l='MpServer', x=446.50, y=79.00, z=275.50], EntityTaintacle['Taintacle'/72, l='MpServer', x=539.50, y=80.00, z=253.50], EntityPixelmon['Murkrow'/201, l='MpServer', x=516.00, y=80.00, z=242.03], EntityTaintacle['Taintacle'/841, l='MpServer', x=510.50, y=72.00, z=334.50], EntityTaintacle['Taintacle'/587, l='MpServer', x=525.50, y=72.00, z=295.50], EntityPixelmon['Magikarp'/204, l='MpServer', x=451.92, y=60.00, z=257.50], EntityPixelmon['Magikarp'/205, l='MpServer', x=487.50, y=61.00, z=293.50], EntityPixelmon['Zubat'/846, l='MpServer', x=466.13, y=56.00, z=305.22], EntityTaintacle['Taintacle'/207, l='MpServer', x=549.50, y=74.00, z=293.50], EntityTaintacle['Taintacle'/719, l='MpServer', x=522.50, y=72.00, z=315.50], EntityPixelmon['Zubat'/847, l='MpServer', x=467.91, y=56.00, z=307.91], EntityPixelmon['Zubat'/848, l='MpServer', x=467.50, y=55.97, z=304.50], EntityTaintacle['Taintacle'/976, l='MpServer', x=532.50, y=71.00, z=324.50], EntityTaintacle['Taintacle'/1106, l='MpServer', x=476.50, y=63.00, z=213.50], EntityPixelmon['Spinarak'/852, l='MpServer', x=516.50, y=71.97, z=250.50], EntityTaintacle['Taintacle'/981, l='MpServer', x=504.50, y=67.00, z=307.50], EntityTaintacle['Taintacle'/857, l='MpServer', x=534.50, y=75.00, z=297.50], EntityTaintacle['Taintacle'/859, l='MpServer', x=446.50, y=70.00, z=319.50], EntityTaintacle['Taintacle'/1118, l='MpServer', x=547.50, y=80.00, z=264.50], EntityTaintacle['Taintacle'/486, l='MpServer', x=526.50, y=76.00, z=282.50], EntityTaintacle['Taintacle'/614, l='MpServer', x=541.50, y=75.00, z=217.50], EntityTaintacle['Taintacle'/1003, l='MpServer', x=473.50, y=73.00, z=221.50], EntityTaintacle['Taintacle'/238, l='MpServer', x=545.50, y=73.00, z=305.50], EntityTaintacle['Taintacle'/884, l='MpServer', x=534.50, y=81.00, z=249.50], EntityTaintacle['Taintacle'/629, l='MpServer', x=501.50, y=74.00, z=307.50], EntityTaintacle['Taintacle'/1144, l='MpServer', x=453.50, y=71.00, z=285.50], EntityTaintacle['Taintacle'/1145, l='MpServer', x=535.50, y=80.00, z=254.50], EntityTaintacle['Taintacle'/764, l='MpServer', x=479.50, y=75.00, z=263.50], EntityTaintacle['Taintacle'/1021, l='MpServer', x=556.50, y=70.00, z=314.50], EntityTaintacle['Taintacle'/254, l='MpServer', x=450.50, y=62.00, z=259.50]]
	Retry entities: 54 total; [EntityTaintacle['Taintacle'/780, l='MpServer', x=506.50, y=76.00, z=268.50], EntityAuraNode['Aura Node'/142, l='MpServer', x=474.50, y=65.50, z=267.50], EntityTaintacle['Taintacle'/144, l='MpServer', x=500.50, y=69.00, z=256.50], EntityTaintacle['Taintacle'/145, l='MpServer', x=505.50, y=73.00, z=303.50], EntityTaintacle['Warped Taintacle'/148, l='MpServer', x=493.50, y=73.00, z=316.50], EntityTaintacle['Taintacle'/660, l='MpServer', x=511.50, y=68.00, z=300.50], EntityTaintacle['Taintacle'/149, l='MpServer', x=469.50, y=72.00, z=310.50], EntityTaintacle['Taintacle'/22, l='MpServer', x=457.50, y=64.00, z=240.50], EntityTaintacle['Taintacle'/150, l='MpServer', x=461.50, y=67.00, z=266.50], EntityTaintacle['Taintacle'/152, l='MpServer', x=526.50, y=76.00, z=271.50], EntityTaintacle['Undying Taintacle'/154, l='MpServer', x=511.50, y=71.00, z=314.50], EntityTaintacle['Taintacle'/155, l='MpServer', x=452.50, y=71.00, z=316.50], EntityTaintacle['Taintacle'/667, l='MpServer', x=488.50, y=64.00, z=310.50], EntityTaintacle['Taintacle'/923, l='MpServer', x=522.50, y=87.00, z=214.50], EntityTaintacle['Taintacle'/539, l='MpServer', x=521.50, y=76.00, z=264.50], EntityTaintacle['Taintacle'/164, l='MpServer', x=443.50, y=75.00, z=303.50], EntityAuraNode['Aura Node'/166, l='MpServer', x=447.50, y=87.50, z=259.50], EntityTaintacle['Taintacle'/551, l='MpServer', x=454.50, y=74.00, z=304.50], EntityTaintacle['Taintacle'/41, l='MpServer', x=488.50, y=65.00, z=246.50], EntityTaintacle['Taintacle'/939, l='MpServer', x=502.50, y=72.00, z=282.50], EntityPixelmon['Magikarp'/1068, l='MpServer', x=482.52, y=62.00, z=293.81], EntityPixelmon['Magikarp'/1069, l='MpServer', x=483.04, y=62.00, z=295.69], EntityPixelmon['Murkrow'/1070, l='MpServer', x=517.50, y=74.00, z=251.50], EntityTaintacle['Taintacle'/687, l='MpServer', x=516.50, y=82.00, z=232.50], EntityItemFrame['entity.ItemFrame.name'/48, l='MpServer', x=502.50, y=67.50, z=155.97], EntityTaintacle['Taintacle'/944, l='MpServer', x=522.50, y=89.00, z=229.50], EntityAuraNode['Aura Node'/178, l='MpServer', x=436.50, y=70.50, z=333.50], EntityAuraNode['Aura Node'/185, l='MpServer', x=489.50, y=89.50, z=405.50], EntityTaintacle['Taintacle'/443, l='MpServer', x=497.50, y=78.00, z=227.50], EntityTaintacle['Taintacle'/700, l='MpServer', x=494.50, y=66.00, z=240.50], EntityTaintacle['Taintacle'/701, l='MpServer', x=502.50, y=70.00, z=266.50], EntityPixelmon['Golbat'/194, l='MpServer', x=513.75, y=76.50, z=243.25], EntityPixelmon['Slowpoke'/196, l='MpServer', x=446.13, y=64.00, z=262.56], EntityTaintacle['Taintacle'/324, l='MpServer', x=483.50, y=64.00, z=253.50], EntityTaintacle['Taintacle'/839, l='MpServer', x=446.50, y=79.00, z=275.50], EntityTaintacle['Taintacle'/841, l='MpServer', x=510.50, y=72.00, z=334.50], EntityPixelmon['Murkrow'/201, l='MpServer', x=516.00, y=80.00, z=242.03], EntityTaintacle['Taintacle'/587, l='MpServer', x=525.50, y=72.00, z=295.50], EntityPixelmon['Magikarp'/204, l='MpServer', x=451.92, y=60.00, z=257.50], EntityPixelmon['Magikarp'/205, l='MpServer', x=487.50, y=61.00, z=293.50], EntityPixelmon['Zubat'/846, l='MpServer', x=466.13, y=56.00, z=305.22], EntityPixelmon['Zubat'/847, l='MpServer', x=467.91, y=56.00, z=307.91], EntityTaintacle['Taintacle'/719, l='MpServer', x=522.50, y=72.00, z=315.50], EntityPixelmon['Zubat'/848, l='MpServer', x=467.50, y=55.97, z=304.50], EntityTaintacle['Taintacle'/1106, l='MpServer', x=476.50, y=63.00, z=213.50], EntityPixelmon['Spinarak'/852, l='MpServer', x=516.50, y=71.97, z=250.50], EntityTaintacle['Taintacle'/981, l='MpServer', x=504.50, y=67.00, z=307.50], EntityTaintacle['Taintacle'/859, l='MpServer', x=446.50, y=70.00, z=319.50], EntityTaintacle['Taintacle'/486, l='MpServer', x=526.50, y=76.00, z=282.50], EntityTaintacle['Taintacle'/1003, l='MpServer', x=473.50, y=73.00, z=221.50], EntityTaintacle['Taintacle'/629, l='MpServer', x=501.50, y=74.00, z=307.50], EntityTaintacle['Taintacle'/1144, l='MpServer', x=453.50, y=71.00, z=285.50], EntityTaintacle['Taintacle'/764, l='MpServer', x=479.50, y=75.00, z=263.50], EntityTaintacle['Taintacle'/254, l='MpServer', x=450.50, y=62.00, z=259.50]]
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Mac OS X (x86_64) version 10.10.5
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 578986072 bytes (552 MB) / 2078277632 bytes (1982 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 1 total; -Xmx3G
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.1808 29 mods loaded, 29 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1808.jar) 
	UCHIJA	Forge{11.15.1.1808} [Minecraft Forge] (forge-1.8.9-11.15.1.1808.jar) 
	UCHIJA	cei{0.1} [Chunk Edge Indicator] (1.8.9-chunkedgeindicator-1.0.jar) 
	UCHIJA	enderutilities{0.5.0} [Ender Utilities] (enderutilities-1.8.9-0.5.0.jar) 
	UCHIJA	Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
	UCHIJA	FTBL{2.0.2} [FTBLib] (FTBLib-1.8.9-2.0.2.jar) 
	UCHIJA	FTBU{2.0.2} [FTBUtilities] (FTBUtilities-1.8.9-2.0.2.jar) 
	UCHIJA	HardcoreDarkness{1.8} [Hardcore Darkness] (HardcoreDarkness-MC1.8.8-1.8.jar) 
	UCHIJA	InventoryPets{1.3.91} [Inventory Pets] (inventorypets-1.8.9-1.3.91.jar) 
	UCHIJA	inventorytweaks{1.60-dev-27-43ecdd2} [Inventory Tweaks] (InventoryTweaks-1.60-dev-27.jar) 
	UCHIJA	IronChest{6.0.115.759} [Iron Chest] (Iron-Chests-Mod-1.8.9.jar) 
	UCHIJA	JEI{2.28.7.174} [Just Enough Items] (jei_1.8.9-2.28.7.174.jar) 
	UCHIJA	Thaumcraft{5.2.4} [Thaumcraft] (Thaumcraft-1.8.9-5.2.4.jar) 
	UCHIJA	JEIAddons{0.12.0.57} [Just Enough Items Addons] (JEIAddons_1.8.9-0.12.0.57.jar) 
	UCHIJA	journeymap{5.1.3} [JourneyMap] (journeymap-1.8.8-5.1.3-fairplay.jar) 
	UCHIJA	LunatriusCore{1.1.2.32} [LunatriusCore] (LunatriusCore-1.8.9-1.1.2.32-universal.jar) 
	UCHIJA	testdummy{1.0} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.9b.jar) 
	UCHIJA	MoreFurnaces{1.5.0} [More Furnaces] (MoreFurnaces-1.5.0-MC1.8.9.jar) 
	UCHIJA	samsmountedpearl{1.0.0} [Mounted Pearl] (MountedPearl-1.8.9-1.0.0.jar) 
	UCHIJA	pixelmon{4.2.3} [Pixelmon] (Pixelmon-1.8.9-4.2.3-universal.jar) 
	UCHIJA	randomthings{3.6.6} [Random Things] (RandomThings-MC1.8.9-3.6.6.jar) 
	UCHIJA	redstonepaste{1.7.2} [Redstone Paste] (redstonepaste-mc1.8.8-1.7.2.jar) 
	UCHIJA	rftools{4.23beta37} [RFTools] (rftools-1.8.9-4.23beta37.jar) 
	UCHIJA	Schematica{1.7.7.142} [Schematica] (Schematica-1.8.9-1.7.7.142-universal.jar) 
	UCHIJA	sciapi{1.2.0.1} [SciAPI] (SciAPI-1.2.0.1.jar) 
	UCHIJA	SGCraft{1.10.1} [Greg's SG Craft] (SGCraft-1.10.1-mc1.8.9.jar) 
	UCHIJA	SimpleDimensions{1.3} [Simple Dimensions] (SimpleDimensions-1.3.jar) 
	UCHIJA	stellarsky{0.2.2.4} [Stellar Sky] (Stellar Sky-0.2.2.4.jar) 
	Loaded coremods (and transformers): 
ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
  
Java8CheckerCoremod (Pixelmon-1.8.9-4.2.3-universal.jar)
  
FMLPlugin (InventoryTweaks-1.60-dev-27.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (HardcoreDarkness-MC1.8.8-1.8.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  net.fybertech.nwr.NowWithRendering
LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
  lumien.randomthings.asm.ClassTransformer
	Launched Version: 1.8.9-forge1.8.9-11.15.1.1808
	LWJGL: 2.9.2
	OpenGL: AMD Radeon HD - FirePro D300 OpenGL Engine GL version 2.1 ATI-1.32.25, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (UK)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz

the github page for SD is here: https://github.com/lumien231/Simple-Dimensions
hope that helps

**Comment by Abastro** [comment]
No crash appeared with only Stellar Sky and Simple Dimensions(1.3).
Please reopen this issue with your modlist and all possible mods which could have effect with the dimension.
