### ISSUE TITLE
dimension crash: reopened

### ISSUE THREAD

**Issue by superon** [Abastro/StellarSky#53]
[crash-2016-04-11_10.59.59-client.txt](https://github.com/Abastro/StellarSky/files/212708/crash-2016-04-11_10.59.59-client.txt)

**Comment by Abastro** [comment]
What is your modlist and what mods are related to dimensions?

**Comment by superon** [comment]
oh yeah sorry:
modlist-serverside (i deleted a few mods which aren't required client-side too just for testing : defuzz-1.2.0, FastLeafDecay-1.8-1.6, journeymap-1.8.8-5.1.3-fairplay [i deleted this client-side too])
FTBLib-1.8.9-2.0.2
FTBUtilities-1.8.9-2.0.2
HardcoreDarkness-MC1.8.8-1.8
inventorypets-1.8.9-1.3.91
Iron-Chests-Mod-1.8.9
LunatriusCore-1.8.9-1.1.2.32-universal
mcjtylib-1.8.9-1.8.1beta10
MmmMmmMmmMmm-1.9b
MoreFurnaces-1.5.0-MC1.8.9
Morpheus-1.8.9-2.0.57
MountedPearl-1.8.9-1.0.0
netherportalfix-mc1.8.9-2.1.6
Pixelmon-1.8.9-4.2.3-universal
RandomThings-MC1.8.9-3.6.6
redstonepaste-mc1.8.8-1.7.2
rftools-1.8.9-4.23beta37
Schematica-1.8.9-1.7.7.142-universal
SciAPI-1.2.0.1
SGCraft-1.10.1-mc1.8.9
SimpleDimensions-1.3
Stellar Sky-0.2.2.4
Thaumcraft-1.8.9-5.2.4

client-side is the same except additions of : 1.8.9-chunkedgeindicator-1.0, InventoryTweaks-1.60-dev-27 and jei_1.8.9-2.28.7.174/JEIAddons_1.8.9-0.12.0.57 and the removal of netherportalfix-mc1.8.9-2.1.6... i shall try with netherportalfix also removed from server...

related to dimensions:
mapping mods: ftbLib/ftbUtilities (having a mapping gui), journeymap.
SGCraft: to traverse between dims
Stellar Sky and SimpleDimensions as previously listed.
maybe mcjtylib has something in it too as this is required for "RFTools Dimensions" (though i'm not using that)

**Comment by superon** [comment]
i should probably have added that this crash happens to the client and only when connected to the server.

**Comment by Abastro** [comment]
So you mean on dedicated server environment?

**Comment by superon** [comment]
ermm, i thinks so, not really up with all the terminology(a server set up for multiplayer)... i can invite you to join/test too if that helps?

**Comment by Abastro** [comment]
Okay, sorry for that; It was indeed related with the SimpleDimensions mod.

**Comment by Abastro** [comment]
Problem with SimpleDimensions mod, it should not access MinecraftServer to get world name.

**Comment by lumien231** [comment]
Would you mind elaborating on that? I only use MinecraftServer to get the map storage of the overworld & the world info of the overworld.

**Comment by Abastro** [comment]
Yes that is the problem. Since there is no World in MinecraftServer on client logged in dedicated server, getting dimension name from client should not use MinecraftServer.
