### ISSUE TITLE
no daylight (0.2.2.5)

### ISSUE THREAD

**Issue by superon** [Abastro/StellarSky#54]
don't know if it's specific to this update or maybe even it's just me, but i can't see daylight anymore...   i can see the sun but the sky stays dark:(
following your suggestion i tried /unlock, unfortunately this was a command for another mod i have installed that did something i really didn't want...
![2016-04-12_11 00 53](https://cloud.githubusercontent.com/assets/5957924/14456857/f4417294-009e-11e6-984e-baf6d395277f.png)
i have tried setting the sun to 10 (on the server and the client)...
also where is the "lock button"  alluded to un the config file as being toplight or bottom left if i recall correctly?  :/

**Comment by Abastro** [comment]
No..
not unlock, but /locksky false.
And the config is on the client configuration.
Try that and come again if it does not work.

**Comment by superon** [comment]
ahhh yes! thank you, now i have daylight again, i also have an issue with "/time set day" causing a server crash/hang though...
[crash-2016-04-12_11.32.35-server.txt](https://github.com/Abastro/StellarSky/files/214792/crash-2016-04-12_11.32.35-server.txt)

**Comment by Abastro** [comment]
Make it as separate issue.
