### ISSUE TITLE
set time day crash/hang

### ISSUE THREAD

**Issue by superon** [Abastro/StellarSky#55]
[crash-2016-04-12_11.32.35-server.txt](https://github.com/Abastro/StellarSky/files/214797/crash-2016-04-12_11.32.35-server.txt)
after which i could not relog because i considered still logged in (1/20).

**Comment by Abastro** [comment]
Okay, I'll fix that in few hours.

**Comment by superon** [comment]
thanks again, you are too good to me

**Comment by Abastro** [comment]
Fixed on d61f66fb1bdf34546000d6f3167141e2e2d8ca93d61f66fb1bdf34546000d6f3167141e2e2d8ca93.

**Comment by Abastro** [comment]
Fixed on commit d61f66fb1bdf34546000d6f3167141e2e2d8ca93.
