### ISSUE TITLE
launch crash with 0.2.2.6

### ISSUE THREAD

**Issue by superon** [Abastro/StellarSky#56]
this happened to the dedicated server:
[crash-2016-04-13_00.33.53-server.txt](https://github.com/Abastro/StellarSky/files/216148/crash-2016-04-13_00.33.53-server.txt)
running these mods:
![screen shot 2016-04-13 at 00 38 04](https://cloud.githubusercontent.com/assets/5957924/14478699/066ca7d8-0110-11e6-8b0e-2aa581b00f1d.png)

**Comment by Abastro** [comment]
Fixed on latest b versions.
