### ISSUE TITLE
Literal blue moon (read for more context)

### ISSUE THREAD

**Issue by Sunconure11** [Abastro/StellarSky#57]
While a blue moon is usually either an idiom, or refers to an additional full moon that appears during a year, from time to time, during certain atmospheric conditions, the moon can literally appear blue (to an extent). Is such a thing possible, or rather, the moon appearing a different color due to certain circumstances? This usually happens as a result of either volcanic eruptions, or fire leaving particles in the atmosphere.

Also, I have a minor question. Do you plan on adding any kinds of items, such as telescopes, binoculars, and so on? Those would fit in well, and could probably expand what could be added to the mod greatly.

Some sauces, in case no one believes me (a wise man also checks the sources wikipedia gives):

https://en.wikipedia.org/wiki/Blue_moon#Visibly_blue_moon

**Comment by Abastro** [comment]
Simulating atmospheric conditions will be hard, since there is many factors. I think it is something really hard to implement.
And about telescope&binoculars, I'm planning on separate mod about optics. It's called 'Photooptics'.

**Comment by Sunconure11** [comment]
While this mod is meant to be fairly realistic, is there a way to simplify some of these things for you to allow for stuff like this to be pulled off easier?

Also, when/if you manage to pull off photooptics, would it be possible to add quite a bit of integration between it and stellar sky (and maybe stellarium when/if you ever finish that)?

**Comment by Abastro** [comment]
Atm is actually... problem of mod compatibility. It is the problem.

**Comment by Abastro** [comment]
Closing this as the main suggestion is not going to be accepted.
