### ISSUE TITLE
Player wakes up at strange time of day after sleeping in bed.

### ISSUE THREAD

**Issue by PitchBright** [Abastro/StellarSky#6]
When I use default Stellar Sky configs, and go to sleep at night, the player wakes up at what appears to be around 1pm in the afternoon, with the Sun just passed overhead.

When I change it to D:Tick_Offset=3000.0 … I can sleep when it gets dark, and then the Tick changes to 5000 when I wake up, then I jump right back in bed and I wake up again and the tick changes to 2000, and then I jump back in bed and it changes to 23000… and then 20000, 17000 and so on.

I think the Tick Offset is affecting the Wake Up time, in an unexpected way.

**Comment by Abastro** [comment]
Oh there was the serious issue.. I'd fix it.

**Comment by Abastro** [comment]
Fixed on commit [link=https://github.com/Abastro/StellarSky/commit/98399d04bcd2e93b8930ddb897a086ec85a16a96]98399d0[/linke]. It would be on the next version, v0.1.14
