### ISSUE TITLE
Some kind of out of bounds error?

### ISSUE THREAD

**Issue by Sunconure11** [Abastro/StellarSky#60]
http://pastebin.com/NPfsJvCn

**Comment by Abastro** [comment]
Please explain me the circumstances. Does it happen when you get into the server? Or get into a world and get into there again?

**Comment by Sunconure11** [comment]
This happens when I enter a server that has the latest build of this mod installed, and the clientside has it too.

**Comment by Abastro** [comment]
What was your config settings for server and client?

**Comment by Sunconure11** [comment]
http://pastebin.com/xDdc6dVf

**Comment by Abastro** [comment]
That's strange, it is default settings, but I couldnt reproduce that bug in development environment.
First try the latest version of Stellar Sky. If it works, please close this issue, otherwise come again.

**Comment by Sunconure11** [comment]
This patch fixed it.
