### ISSUE TITLE
No Class Found Error

### ISSUE THREAD

**Issue by Sunconure11** [Abastro/StellarSky#61]
http://pastebin.com/XhmBZVDE

Latest update gives me this crash.

Also, would it be possible to add an option to turn off the clock overlay, for those that might be using minimaps or other mods with GUIs that might interfere with it?

**Comment by Abastro** [comment]
Update Stellar API.
+The gui is fully configurable, you should easily know how to properly configure it if you try to understand.

**Comment by Sunconure11** [comment]
Updating Stellar API helped.

Though I'm curious as how to turn off the HUD, or get out of view. Is there any relevant info on that?

**Comment by Abastro** [comment]
Read the curseforge project, There is following explanation:

Current time, day and year is shown on the HUD. It can be manipulated by pressing key 'U' (Change Time Info Text).

**Comment by Sunconure11** [comment]
Ah.

**Comment by Sunconure11** [comment]
On a side note, it appears settings for the HUD set up in-game are not truly saved. If I remove the clock HUD for instance, it will be back when I restart MC.

**Comment by Abastro** [comment]
Ah okay, I'll add the feature. (Actually that is for Stellar API)
+ How did you removed it? I know that there are several ways.
