### ISSUE TITLE
Stars disappear when you look at them directly (crosshair on the stars) and come back when you aren't look directly

### ISSUE THREAD

**Issue by Sunconure11** [Abastro/StellarSky#62]
Basically what it says on the tin, some kind of weird graphical issue makes stars disappear when you look at them directly, with the crosshair on them.

**Comment by Abastro** [comment]
What version are you using?

**Comment by Sunconure11** [comment]
Currently, Stellar Sky-0.1.4.6, though I plan to update to later builds for my modpack soon.

**Comment by Abastro** [comment]
Update.
