### ISSUE TITLE
Ominous black line in the west direction of worlds

### ISSUE THREAD

**Issue by Sunconure11** [Abastro/StellarSky#63]
https://www.dropbox.com/s/hhwttqs7hjo98tq/Screenshot%202016-06-12%2009.25.52.png?dl=0

If this is intentional, is there a way to turn this off?

**Comment by Abastro** [comment]
Please provide configuration files.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/xt6hkssg2tpehxs/configstellars.zip?dl=0

**Comment by Abastro** [comment]
Could you specify your Graphic Driver and OS?
And please provide logs.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/403jcomd2a2cqfa/fml-client-latest.log?dl=0

Log from last playthrough

GPU: GTX 760

OS: Windows 10

**Comment by Abastro** [comment]
Is this version works?
[Stellar Sky-0.1.5.3.temp.zip](https://github.com/Abastro/StellarSky/files/311844/Stellar.Sky-0.1.5.3.temp.zip)

**Comment by Sunconure11** [comment]
Yes, that works.

**Comment by Abastro** [comment]
@Sunconure11 Then I'd make it default, and make those part configurable.

**Comment by Abastro** [comment]
Fixed on commit 9ecacdfb47bbc3f6b7d8a6ec1788fd4c7eabe16a (v0.1.5.3b)
