### ISSUE TITLE
No Sky, no Gui at all

### ISSUE THREAD

**Issue by derSchotte** [Abastro/StellarSky#66]
Hi,

i installed Stellar Sky and Optifine with Shaders to my ModPack and all works fine. then i updated my NVidia Geforce Driver and your mod kills the whole GUI if shaders are enabled.

MC 1.9.4 / Forge 12.17.0.1968 / StellarSky 0.4.5.2.1 / StellarAPI 0.4.4.1.0 / GeForce 368.39

**Comment by Abastro** [comment]
Driver update kills Rendering? That's interesting.
I'll do some research on this part, and find fix on compatibility with shader mod & packs.

But still, Stellar Sky is officially not compatible with shader mods and provide nearly no support on that part. This is not something that can easily be fixed, which can take a month.

**Comment by derSchotte** [comment]
here is a scrennshot and the last logfile if you need it...

[http://imgur.com/bYRqn7J](url)
[http://kunde.2way-design.de/minecraft/fml-client-latest.log](url)

**Comment by Abastro** [comment]
The links were somewhat broken, please fix it not to link github/url.
Except for that, thanks for the information! Shader mod incompatibility might get able to be resolved.

**Comment by derSchotte** [comment]
fixed :D

**Comment by Abastro** [comment]
Well, would you post the log file here as .zip file? It takes time so much while opening the log page.
Also what are the old version and new version of NVidia Geforce Driver on the update?

**Comment by derSchotte** [comment]
hi,

I'm glad, i can help [ZIP](http://kunde.2way-design.de/minecraft/fml-client-latest.zip)

**Comment by Abastro** [comment]
Thanks, I'll what changed on the version, and its effect on shader mods and Stellar Sky mod.

**Comment by Abastro** [comment]
Temporal fix is pending...

**Comment by Abastro** [comment]
Please check again.

**Comment by Abastro** [comment]
Guess this should be fixed, report this issue again if there are some bugs left.
