### ISSUE TITLE
Stellar Skies 0.1.5.7 + Stellar API 0.1.3.8 crash when opening world

### ISSUE THREAD

**Issue by Volxx** [Abastro/StellarSky#67]
So I wanted to try out this mod because it looked pretty frickin badass, so I installed Stellar Skies 0.1.5.7 and Stellar API 0.1.3.8 for 1.7.10 running off Forge 10.13.4.1614 and fell off my bed laughing when I saw it crashed my game after making a world and trying to go into it.

Got the crash report here: http://pastebin.com/VjU78Lzu

I also tried putting SciAPI in there because my mind is a mysterious thing, and it still crashes even without it. Any ideas on why this happens? Its a fresh install of Forge and the mods, so I don't know why it'd crash. I have a good feeling it's because I need to get Stellar API 0.1.3.7 instead, so I'll see if that fixes it.

Thanks in advance!

EDIT: Tried it using Stellar API 0.1.3.7b and that didn't do anything. BTW, it crashes I think when it says "Grabbing information from Dimension Overworld" or something like that.

**Comment by Abastro** [comment]
This is really unexpected, seems like minecraft itself has problem.
First, try giving more RAM to minecraft. Also, try without Custom Main Menu.

**Comment by Volxx** [comment]
I dont think the log will prove very useful, because it is actually extremely short, but it DOES have an error at the end, so here's that:

http://pastebin.com/Uk17ZNMS

Getting rid of Custom Main Menu did nothing. And I tried allocating up to 3 gigabytes of RAM and that also didn't help at all, and I can't really go higher than that because the system and all that stuff is using 40% of my memory already, and I only have 6 GB of RAM in my laptop. Yes, it is a laptop.

(If this matters, I have Intel (R) HD Graphics 5500 in this thing, thought I should point that out)

**Comment by Volxx** [comment]
So I actually just tried starting up Minecraft without any mods on it, but still with Forge, and it still crashed. So I'm gonna try reinstalling Minecraft and Forge and see if that fixes anything.

**Comment by Volxx** [comment]
Reinstalled Minecraft and Forge and it works fine now. Thanks for the help!
