### ISSUE TITLE
Completely black screen in-game with Stellar Skies 0.1.5.7 + Stellar API 0.1.3.8 

### ISSUE THREAD

**Issue by Volxx** [Abastro/StellarSky#68]
I honestly don't know why I'm having so much trouble with these mods, but I'm not giving up on making them work. Really sorry for all this, but onto the problem.

So, I got rid of Slimevoid Library and Little Blocks, and going into my worlds works just fine. When I get in, however, I can't see anything. All I can see is the chat, my hotbar, and Journey Map in the corner, but thats it. Interacting with the world is fine, I can still break blocks and hear slimes and stuff, and the map view works fine, but the world is just completely black and I have no idea why. Allocated 3 GB of RAM to see if that did anything, no luck. Getting rid of OptiFine didn't do anything either. Graphics drivers are all up to date too. There's also some really bad lag at only 1-3 FPS but that's understandable because there's over 100 mods in there.

Logs: http://pastebin.com/d6Ext0Xe

Any ideas? Hopefully this will be the last problem I'll have with this.

**Comment by PitchBright** [comment]
Can you pastebin your Stellar Sky configs? I just wanna peek at them.

**Comment by PitchBright** [comment]
Thaumicexploration seems to be a problem. Try removing it.

**Comment by Volxx** [comment]
Yup, here they are.
http://pastebin.com/rS7xnSuS

Thaumic Exploration? K, ill try that.

**Comment by PitchBright** [comment]
D:Mag_Limit=6.0 is pretty high... and will impact FPS... unless you've got a good machine. Try it at 2.0 or 3.0 just as a test.

**Comment by Volxx** [comment]
Thaumic Exploration made no difference, still a black screen. I'll try that though

**Comment by Volxx** [comment]
Btw, those are both new config files. I tried both Stellar Skies and Stellar API like that before and it didn't do anything and worked perfectly fine, so from that I'd guess some other mod is causing the problem.

**Comment by Volxx** [comment]
Set it to 3.0 and then 2.0 and neither made any difference

**Comment by Abastro** [comment]
Mag Limit is totally not related with the problem. Do you have any shader mods?

**Comment by PitchBright** [comment]
No I know it's not the cause of the black screen... but it does affect FPS. That's the only reason I was curious as to what he had it set to.

**Comment by Volxx** [comment]
Nope, I have optifine but shaders werent added into optifine until 1.8.9

**Comment by Volxx** [comment]
Waaaaaaaaaait a second an old shader mod i used to use with it somehow snuck into the mods folder without me knowing XD lemme get rid of that and retry

**Comment by Volxx** [comment]
God im an idiot...that fixed it. Sorry about all this XDDDDD

**Comment by Abastro** [comment]
Glad that fixed it. :)

**Comment by Volxx** [comment]
Also the bad lag was because this one mod was spawning a shitton of mobs all over the place and there were so many it dropped my fps from 30 to 1
