### ISSUE TITLE
Moon is small.

### ISSUE THREAD

**Issue by PitchBright** [Abastro/StellarSky#7]
The moon does feel a little bit small, is it easy for you to increase it's size? It should be the same size as the Sun.

**Comment by Abastro** [comment]
I'd also make some config option for that.

**Comment by PitchBright** [comment]
It works! Thanks so much for adding this feature!

**Comment by PitchBright** [comment]
Reopening for minor issue with the moon. It gets smaller and disappears when you look directly at it.
http://imgur.com/a/lnrfh

**Comment by Abastro** [comment]
Sorry, that one is bug separated with this suggestion.
