### ISSUE TITLE
Feature Request: Star rendering sharpness config option

### ISSUE THREAD

**Issue by PitchBright** [Abastro/StellarSky#70]
As per discussion, users requesting configuration control of sharpness/blurriness on star rendering. 

For reference:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1444983-wip-stellar-mods-stellar-sky-stellarium?comment=366

and #69

**Comment by Abastro** [comment]
Please check if v0.5.5.1.5 192e10bfaed943dee58b2426f082e4806dfad76a is sufficient.
@PitchBright, @Neptium (+ any suggestion by anyone would be greatly appreciated!)

**Comment by Abastro** [comment]
Post issue again when it seems to be not sufficient. (No reply for a long time)
