### ISSUE TITLE
Feature request, and possible incompatibility issue

### ISSUE THREAD

**Issue by Sunconure11** [Abastro/StellarSky#71]
On 1.7.10 (as well as 1.10.2), your shaders are not 100% compatible with Dynamic Surroundings, and cause stuff such as bright skies during rain (while this can happen IRL, I don't think this is intended) and sandstorms. Since you have an unofficial port of Dynamic Surroundings for 1.9.4 and 1.10.2, would it be possible to fix any issues with the shaders here that might cause problems with the two mods?

Also, an option to turn off some of the more advanced shaders might be worthwhile, as it would allow for players with weaker systems to tolerate it.

**Comment by Abastro** [comment]
Did raining make sky brighter sometimes?
And I'm afraid that I can't make a config option to return to previous look. It's what I wanted to do, but I just couldn't because of the difference in format.
+ Performance issue mostly caused by shaders can be reduced by decreasing the atmosphere fragment number.

**Comment by Sunconure11** [comment]
Here is the issue on 1.10.2:

https://www.dropbox.com/s/thki96b3d45hu5k/Screenshot%202016-07-05%2008.55.36.png?dl=0

It is identical on 1.7.10 as well. I suggest seeing about implementing the fix across all versions, since it might be a bit before everyone finds out your unofficial port of Dynamic Surroundings.

It also happens with sandstorms.

**Comment by Abastro** [comment]
There is the case that sky seems its not raining if rain strength is too small.( On reality), but Ill investigate this.
Note; 1.7.10 is not supported. Only critical bugs would be fixed.

**Comment by Abastro** [comment]
Hope this was fixed.
