### ISSUE TITLE
[Crash] Crash when changing dimension

### ISSUE THREAD

**Issue by nikkimas** [Abastro/StellarSky#72]
When I change the Dimension, stellar Sky infinitely counts up in the "loading" screen. It flashes. You can move and interact woth the world, but the loading screen pops up and disappears twice a second. When you hit ESC and Disconnect, it crashes. 

Crash Report Here: [http://pastebin.com/EMYE3X2Y](http://pastebin.com/EMYE3X2Y)

MInecraft: 1.10.2
Forge: 12.18.1.2014
Stellar API: 0.5.4.1.2
Stellar Sky: 0.5.5.1.6

Edit:
I made a video capturing the bug. However since I unfortunately were just recording at 30FPS, the loading screen wasn't captured. In the end of the video I crashed. Video: [https://www.youtube.com/watch?v=YDtm-42R2Ys](https://www.youtube.com/watch?v=YDtm-42R2Ys)

**Comment by Abastro** [comment]
Where is the dimension?

**Comment by nikkimas** [comment]
Sry, shouldn't have taken a modded dimension^^" It was "Aromas Dimensional World", but it occurs on every Dimension change. Here is the [fml-client-latest.log](http://puu.sh/qeBYo/ccc4c517c7.log) 

(Sry, 4MB is too big for pastebin :/)

**Comment by Abastro** [comment]
Do you mean that this happens with nether/ the end?
Also, does this happen only with Stellar API & Stellar Sky?
Do you have Stellar Sky on the server side?

**Comment by nikkimas** [comment]
Yes, it happens with nether and end.
When I removed it on the client everything was fine.
No, it caused lag for some players, so I had to remove it :(.

**Comment by Abastro** [comment]
Having Stellar Sky on the server side created lags?
Please post it as separate issue.
And, I'll try to fix the issue with Stellar Sky as client-only, but it'll take time.
(+ Stellar API might need to be on the server)

**Comment by nikkimas** [comment]
It created lags on the client, but people couldnt join with the stellar mods unactive on client, so I removed them on the server Side

**Comment by Abastro** [comment]
Please, create separate issue on the lag with Stellar Sky on the server.

**Comment by nikkimas** [comment]
Shouldn't bee an issue on the mod's side. They have pretty bad PC's and can't use steallar sky in general, but if you still need that, I'll make a new issue.

And I just tested it in a SP world. There it worked fine, so it seems to be really the problem, that the stellar mods aren't on the server

**Comment by Abastro** [comment]
Ah sorry, I misunderstood that.
(Any performance information from the players would be greatly appreciated, but anyway)

**Comment by nikkimas** [comment]
I don't really know. All they said was: "Under 10 FPS! Plz remove Stellar Sky". I told them to give mc more RAM but they said the problem was still there. So that's all the performance info I have :D

**Comment by Abastro** [comment]
Will be fixed on the next version.
