### ISSUE TITLE
Stellar Sky might be a CPU hog

### ISSUE THREAD

**Issue by Sunconure11** [Abastro/StellarSky#73]
While having someone look at my pack to see what is causing an unrelated issue, they discovered that Stellar Sky, at least on 1.7.10, is eating a lot of CPU power.

https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/870

If it is possible, see if you can reduce CPU usage on later versions of MC, since 1.7.10 is no longer supported by you.

**Comment by Abastro** [comment]
Must be tested on 1.10, since cpu performance got greatly improved on recent versions.

**Comment by Abastro** [comment]
Closing this since it's based on 1.7.10 which is a far outdated.
