### ISSUE TITLE
Incompatibility with optifine shaders

### ISSUE THREAD

**Issue by CKTheUltimate** [Abastro/StellarSky#77]
The sky looks terrible(the sky is textured with the ground) when I am using a shader.Can you add support to shaders?

**Comment by Abastro** [comment]
Sorry but no. Those shader mods does not allow other mods to use shaders, which is necessary in my case.
Though I'm looking for ways to make it compatible, so it'll be supported when there comes some ways.

Issue #66 is about these shader problems, closing this issue as duplication.
