### ISSUE TITLE
Weird sky flickering

### ISSUE THREAD

**Issue by Milii20** [Abastro/StellarSky#78]
Greetings, i found a weird bug which is probably an incompatibility between the mods i have
With forge 2185 in minecraft 1.10.2, StellarApi 0.5.4.1.3 and stellarSky 0.5.5.1.7 and the modlist :
![modslist](https://cloud.githubusercontent.com/assets/10578092/21553766/073af128-cde9-11e6-91ce-5550268ba84d.JPG)

i found my sky flickering sometimes when i join the server, and i confirmed two things: it's not clientside (because restarting client does nothing, and the sky keeps on flickering until i restart the server), and it's not just my computer (another friend joins and has exactly the same problem), but i cant seem to find a solution for it, neither find if it's a conflict or not (tried taking mods out but same thing, i start the server back again, works fine  and arround an hour later sky starts flickering on daytime)

Thank you very much

**Comment by Abastro** [comment]
Sorry for late reply. How does it flicker?
Usually something like this is hard to diagnose, but I'll try to locate the problem and fix it.

**Comment by Milii20** [comment]
Greetings! it flickers like going day-night but several times per second (my head started hurting 5 seconds after i logged into the server), the sky changes from lighted up to totally dark, but it doesn't stop the time (day night cycle still happens), it doesn't affect neither fps nor tps, and it doesnt happen when the time is supposed to be night.
What i think may be is probably an incompatibility  with the Harvest Festival mod, which introduces it's own weather mechanics (and i dont know if it doesn't affect the day-night cycle also)

 It starts all of the sudden, and restarting the server seems to fix it (restarting clients without restarting the server does nothing), but unless i set up something for restarting the server every 2 hours i coudn't find any other way to fix it, neither was able to keep testing

**Comment by Abastro** [comment]
Then it seems to be the problem on the side. I'll take a look on it, though.

**Comment by Abastro** [comment]
Probably incompatibility with the Harvest Festival. Can't be diagnosed and fixed here.

**Comment by Abastro** [comment]
Pleaes reopen this issue if this still bothers you.
