### ISSUE TITLE
Blue Cylinder Appearing Around Character

### ISSUE THREAD

**Issue by HypnoPants** [Abastro/StellarSky#79]
I just got stellarsky today and I noticed after checking my inventory that a giant blue cylinder appeared... seems to be focused on my head.

![blue](https://cloud.githubusercontent.com/assets/22647132/23499545/c4eb0678-fee9-11e6-9fe5-d8cb468dce4e.png)

**Comment by HypnoPants** [comment]
Also really happy with CelestialSettings.cfg

I edited D:Minimum_Sky_Render_Brightness=0.01
The 0.01 brings the natural night light level down so far it looks like a horror game, and lets you see the beautiful sky without so many distractions.

**Comment by HypnoPants** [comment]
Ah, figured it out... the problem was with photoptics.

**Comment by PitchBright** [comment]
@HypnoPants please close the Issue.
