### ISSUE TITLE
Moon resizes itself when player looks at it.

### ISSUE THREAD

**Issue by PitchBright** [Abastro/StellarSky#8]
Minor issue with the moon. It gets smaller and disappears when you look directly at it.
http://imgur.com/a/lnrfh

**Comment by Abastro** [comment]
When does this issue occur? I cannot reproduce this bug indev / outdev.

**Comment by PitchBright** [comment]
In a Flatworld, try setting your longitude & latitude to the North Pole, and use gamerule doDaylightCyle false to freeze time. Then do /time add 24000 repeatedly to see the moon cycle around the sky until it comes into view. Then when you view it, you should be able to see the problem, most of the time.

**Comment by Abastro** [comment]
Sorry, I cannot reproduce the bug in the condition.

**Comment by PitchBright** [comment]
That's really weird. Have you tried doing it outside of dev env?

**Comment by Abastro** [comment]
Yes.

**Comment by PitchBright** [comment]
Ive run it on a clean install, with no other mods present. If you've done the same then the only thing I can think of is a Forge version difference. Try it on 1448.

**Comment by Abastro** [comment]
It just works well on 1448.
http://puu.sh/l7LMc/211c02c5ab.png
So please provide any conditions that might have related with this issue.

**Comment by PitchBright** [comment]
I'm not having any luck recreating it either. I'm not sure why. I've tried a million things, and it's not happening anymore, so I'll close this down and reopen it if resurfaces. It could very well have been a typo on my config file or something that made the moon act funny. I had originally tried the Moon's Brightness at -12, because I assumed "Brightness" meant "Magnitude".

**Comment by PitchBright** [comment]
Also worth nothing, if the player doesn't delete their config file from v14, before installing v15… they get some really odd behaviour. It's best to recommend that people delete their config file and start with a new one for v15.

**Comment by PitchBright** [comment]
I figured this out, I think. 

It has to do with the player's video options "View distance" being set to "4"… and the moon being at an exact angle that; depending on how you are looking at it… it's either under the view distance, or over the view distance (and not visible).

**Comment by Abastro** [comment]
Oh, I thought that it would not be affected by view distance;
