### ISSUE TITLE
Ticking Entity Crash

### ISSUE THREAD

**Issue by brisingraerowing** [Abastro/StellarSky#80]
I am not sure whether the crash is caused by this mod or Advanced Rocketry, so I will post to both.

MC: 1.10.2
Stellar Sky: 0.5.5.1.7
Forge: 12.18.3.2239

I am getting a ticking entity crash after launching myself into the air above the world build height limit (I was at about Y = 800) using a booster rocket from another mod. As I dropped down, the instant I hit Y = 255 the crash happened.

[Crash Log](https://gist.github.com/BrisingrAerowing/d65e38824341c8e275684ce85e43d817)

I still use 1.10.2 as some of my base mods haven't updated yet, although most of them have.

**Comment by Abastro** [comment]
Oops; I got a loophole there. Should be fixed on the next version.
