### ISSUE TITLE
Compatibility with Botania's Garden of Glass Sky

### ISSUE THREAD

**Issue by Poshtester63** [Abastro/StellarSky#81]
Hey there.

I don't know if this is possible, but could you include compatibility with Botania's Garden of Glass Sky? More specifically have the rainbow and planets overlay on top of the Stellar Sky's night time sky?

I understand if this isn't possible, just that if it's not possible, I'll have to choose between the two (Hard Decision).

Or maybe - even though its not realistic, could you incorporate a similar 'rainbow' and planet shapes?

Thank you anyway.

**Comment by Abastro** [comment]
Sorry for late reply.
This is hard because there is only one way to modify sky rendering: set sky renderer. So no way to incorporate sky of other mods.
But I'll try. 
Also I'll probably introduce ring systems.

**Comment by Abastro** [comment]
Let me know what happens with the recently released version. You need to enable Render_Other_Modded_Skybox which is in dimension-specific settings.

**Comment by Abastro** [comment]
Commit ab2710cdca87305e21bbb345f2fe10500c30a8d6 should be satisfactory.
