### ISSUE TITLE
1.11.2 Gui Settings not staying :/

### ISSUE THREAD

**Issue by TwitchtvCarbs** [Abastro/StellarSky#82]
Having a really frustrating issue where when I close my game then reopen it, I have to press u then switch it to stellarsky for the clock to show up. This is really frustrating since I'm making a modpack which id like to have it on by default but everytime I go to start a new world its gone and I have to turn it on in the menu again :/

**Comment by Abastro** [comment]
Oops. Should be fixed on the overhaul I'm currently working on.

**Comment by TwitchtvCarbs** [comment]
Awesome! Looking forward to the update :3

**Comment by Abastro** [comment]
This should be issue of Stellar API. Currently working on it, will be fixed. :)
EDIT: Okay, problem of Stellar Sky. Still, will be fixed.

**Comment by Abastro** [comment]
The fix will be uploaded on the next version.
