### ISSUE TITLE
1.11.2 v0.6.5.1.4 Null Pointer Exception Crash When Joining Server

### ISSUE THREAD

**Issue by TwitchtvCarbs** [Abastro/StellarSky#84]
Have a user that is getting this crash when they try to join the server.

https://pastebin.com/ShMw9mtC

Those dirty null pointers :P

**Comment by Abastro** [comment]
Well, this is unexpected... I'll try to trace it.

**Comment by Abastro** [comment]
What mods do you have? It seems that the world is not yet loaded on the first client tick...
Anyway, there will be an unhacky workaround on the stellar api side on the next version.
