### ISSUE TITLE
ThermalDynamics Viaduct and StellarSky crash

### ISSUE THREAD

**Issue by An-Sar** [Abastro/StellarSky#85]
This crash occurs when the player enters a viaduct, which renders a view of the player moving through the pipe.

https://pastebin.com/K2mus5Ax

A related issue was opened over at CoFH: https://github.com/CoFH/Feedback/issues/334

**Comment by Abastro** [comment]
This rather looks like a compatibility problem with  Astral Sorcery. It replaces the sky, so... But I'll try to fix it.

**Comment by An-Sar** [comment]
I was able to produce the crash just StellarSky and the CoFH mods installed. 

Originally I was testing with and without astral sorcery because it was also installed during the original crash, and my first thought was the same.

**Comment by Abastro** [comment]
Then please provide a crash without the astral sorcery. Also doing so on vanilla launcher is preferable.

**Comment by An-Sar** [comment]
Here is a crash with the base set of dependencies for both mods

https://pastebin.com/AAfWLDnd

**Comment by Abastro** [comment]
Hmm.. I guess it's because Stellar Sky does not support the viewer entity(simulator?).
I think there is no need to handle individual compatibility case - Might make a placeholder for this.

**Comment by Abastro** [comment]
Should be fixed on the Stellar API side. (The fix will be applied on the next version of Stellar API)
