### ISSUE TITLE
Stellar Sky causes all Galacticraft planets to render as completely black worlds

### ISSUE THREAD

**Issue by Diufool** [Abastro/StellarSky#86]
Minecraft version: 1.7.10
Forge version: Forge 10.13.4.1614-1.7.10

Single player (SSP) or Multiplayer (SMP)?
Single player, Multiplayer untested

GalacticraftCore-1.7-3.0.12.497
Galacticraft-Planets-1.7-3.0.12.497
Stellar API-0.1.3.8
Stellar Sky-0.1.5.7

Stellar Sky works in the Overworld and the End as intended but having Stellar Sky demolishes the rendering of any of the Galacticraft dimensions. I can disable Stellar Sky and Galacticraft works fine but Stellar Sky is such a great mod that I want to keep.

Screenshot of me looking up at the sky on the moon(it does this when i tested on asteroids also)
https://user-images.githubusercontent.com/30983986/29252149-bc941812-8016-11e7-9b42-569bb33ff972.png

This is me looking at the ground(same thing as asteroids)
https://user-images.githubusercontent.com/30983986/29252168-0ee7e076-8017-11e7-9d35-37191c69e575.png

No Crash Occurred

**Comment by Abastro** [comment]
Well, sorry, support for 1.7.10 is ended. But I will check for later versions if it happens.
EDIT: diagnosed the same issue on the recent version(1.11.2). Though, It's hard for me to diagnose the issue. It MAY help to report this issue on the side as well.
(In detail : Stellar Sky is not going to patch or affect the Moon dimension in any way. So this couldn't be a typical issue)

**Comment by Abastro** [comment]
Stellar API issue, please post on there.

**Comment by Abastro** [comment]
Fixed it on 1.11.2, anyway.
