### ISSUE TITLE
Adds "=====" to Custom Main Menu buttons with images

### ISSUE THREAD

**Issue by BBoldt** [Abastro/StellarSky#88]
I don't know how or why this is a problem, but it seems something in Stellar Sky is breaking something in [Custom Main Menu](https://minecraft.curseforge.com/projects/custom-main-menu). 

Here is my custom main menu without Stellar Sky:
![](https://i.imgur.com/4RAYXyL.jpg)

And here it is with:
![](https://i.imgur.com/UHd6YHy.jpg)

Made a test pack with the minimum amount of mods required to replicate this issue to make things as easy as possible.

- Forge 2481
- CustomMainMenu-MC1.12.1-2.0.7.jar
- ResourceLoader-MC1.12.1-1.5.3.jar
- Stellar API-0.7.4.1.1
- Stellar Sky-0.7.5.1.5

Here are the specific configuration files that my custom main menu is based upon as well, just goes in the main minecraft directory:
https://www.dropbox.com/s/kj2lqx6698qxyna/MENUTEST.zip?dl=0

**Comment by Abastro** [comment]
Well, I was blind =P
It was because of the lang file not cleaned-up.
Going to upload the fixed version.

**Comment by BBoldt** [comment]
Oh wow, I think i've messed up lang files like that myself before. Strange how it can affect so much.

Thanks for the fix!
