### ISSUE TITLE
Server's DayTime nbt data gets changed when starting v0.1.15 

### ISSUE THREAD

**Issue by PitchBright** [Abastro/StellarSky#9]
There's something about this version of the mod that changes the world's DayTime nbt data in the world's "level.dat" file.

Our world is very old (roughly 3.5 years old IRL), and we've had it going for a long time so the DayTime is extremely high, but this gets changed when the mod is started on the server.

Here is a before and after picture of the level.dat file (see "DayTime") 2 images here: http://imgur.com/a/dWAci

Here is the Stellar Sky debug info verifying the change… 2 images here: http://imgur.com/a/2rC9o

**Comment by Abastro** [comment]
I'd inspect into it, but it seems that it might be a forge bug or bug with another mods.
Please post some log for that?

**Comment by PitchBright** [comment]
I don't have log files from when that happened. To recreate the bug in your dev env, set your DayTime and Time nbt's in your level.dat of your test world, to something like 5247194381. Then start up stellar sky, show the debug info for the Year, Day, Tick… and then sleep in a bed. It should change after you sleep.

**Comment by Abastro** [comment]
So this happens after sleeping?

**Comment by PitchBright** [comment]
Yeah, it happens after sleeping for the first time. After that first time, it doesn't happen again… time continues to add up normally.

**Comment by Abastro** [comment]
So had the time displayed on the screen also changed?

**Comment by PitchBright** [comment]
Yeah. The first image was from the moment I started up the world, and the second image is from after I had my first sleep.

**Comment by Abastro** [comment]
What was your configuration settings?

**Comment by PitchBright** [comment]
This is my config file: http://pastebin.com/iSqLsp9W

**Comment by PitchBright** [comment]
Similar issue with Version 17.. where if I set both wake properties to False…. it subtracts ~2,000,000,000 ticks from DayTime and time runs backwards (or crashes if you have NEI installed).

**Comment by Abastro** [comment]
It is intended feature. It should not work when both wake properties is false.
You should totally disable wake system of Stellar Sky to do that.

**Comment by PitchBright** [comment]
I misunderstood. I thought the wake system Enable/Disable… totally overrides the subset of wake alarms. Thanks!
