### ISSUE TITLE
Astral Sorcery Compatability?

### ISSUE THREAD

**Issue by Labreris** [Abastro/StellarSky#90]

**Comment by PitchBright** [comment]
This is an "ISSUE" tracker. Are you asking a question? If so, please use the forums, and close this Issue. If you have an issue to report about Stellar Sky's compatibility with Astral Sorcery, then put a modicum of effort into describing the problem, at least. Please don't abuse GitHub.

**Comment by SimulatorSia** [comment]
@PitchBright That's rather rude

He's asking if you intentionally made any Astral Sorcery compatibility. If you didn't you could just say "no".

**Comment by PitchBright** [comment]
It's not rude, it's the truth. He didn't ask a question, this isn't a discussion forum or a Q&A section for people to ask vague and indescript questions, thereby creating more work for content creators authors by forcing them to probe the question-asker for more information, and in this case... ANY information. It's an Issue Tracker for posting issues that authors need to use to resolve problems. Me explaining that to him was not unwarranted. 

You calling me out for explaining that to him, is an indictment of you, and your level of understanding of what github's Issue Tracker is for. I explained it to him, in no uncertain terms. You excusing the misuse of the Issue Tracker, and assuming that you know exactly what he was asking, does not improve the situation, nor help to curb the continual misuse of github in general. Some authors thank me for taking the time and effort to try to correct the misuse of their issue tracker by lazy or ignorant users, you should not be telling me how I should address the problem... you're not going to find support from the people that actually know better. He is clearly not an experienced user, he edit-deleted his comment and did not close the issue. I checked his github activity history, before responding, and I handled it appropriately.

**Comment by SimulatorSia** [comment]
Alright I'll say the issue then. It's not compatible with Blood Moon, HardcoreDarkness, or GeneralLaymansAestheticSpyingScreen. No need to make a big fuss. I wasn't calling you out. I wasn't aware this wasn't a discussion.

**Comment by Abastro** [comment]
@Labreris Your wording is too vague. Please elaborate it with appropriate descriptions.
@SimulatorSia Make your own issue, please. A compatibility issue with mod A is irrelevant with compat issues with mod B, C or D. Also, it's compatible with HardcoreDarkness, it's just that there is one duplicate feature on both sides. You can find the config settings for dark night in per-world settings.

**Comment by Abastro** [comment]
Closing this as being inactive for months and proper issue replacing this one is created.
