### ISSUE TITLE
client crash while loading

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [Abastro/StellarSky#92]
The client crashes while loading
The crashlog says: "FBO must be enabled for Stellar Sky to run"
but in my options is fboEnable:true

MC 1.12.2
Forge: 14.23.1.2590
StellarSky: v1.12.2-0.5.2.3
[crash-2018-01-16_19.54.24-client.txt](https://github.com/Abastro/StellarSky/files/1636417/crash-2018-01-16_19.54.24-client.txt)

**Comment by Abastro** [comment]
Wow, this shouldn't happen on OpenGL 4.5..
I'll check it. Could you provide the log as well?

**Comment by Abastro** [comment]
Besides are you able to use super secret settings? Do you know graphics card are you using?
EDIT: Try updating the driver.

**Comment by Abastro** [comment]
Check out the latest version, it will fix the issue.

**Comment by 5t0rmr1d3r** [comment]
sorry for not answering, i was offline yesterday.
the last version fixed the issue!

**Comment by Abastro** [comment]
Glad it worked! =)
