### ISSUE TITLE
Crash just after loading in a world

### ISSUE THREAD

**Issue by Gh0st-VX** [Abastro/StellarSky#93]
Just after creating a new world , I get to see the GUI and game for a split second, and then crash. If loading in a pre-existing world, the game crsahes just before it would show the screen. This does not occur with stellar API only.
I think that the change in crash time is due to the sky not being shown for a split second when first creating a world, but being shown instantly when loading an existing one.

Crash log
[crash-2018-01-27_13.41.41-client.txt](https://github.com/Abastro/StellarSky/files/1670106/crash-2018-01-27_13.41.41-client.txt)

Minecraft Log from multiMC:
https://paste.ee/p/V5GWY

I don't know how I would get the required computer specs, but I think they may be important in this case.

**Comment by Abastro** [comment]
GL2.1 is pretty outdated, but it should be supported. I forgot to log the part, so... please would you run this with this file?
https://www.dropbox.com/s/cspq247i75e8tz8/Stellar%20Sky-1.12.2-0.5.2.7.jar?dl=0

**Comment by Gh0st-VX** [comment]
It crashed in a similar situation as before. It might be best for me to figure out how to upgrade from GL2.1.

Crash log
[crash-2018-01-29_17.05.16-client.txt](https://github.com/Abastro/StellarSky/files/1674530/crash-2018-01-29_17.05.16-client.txt)

Minecraft log from multiMC:
https://paste.ee/p/bRnZZ

**Comment by Abastro** [comment]
Still just a RuntimeException, without a single log? Weird...
Are you able to use Super Secret Settings in Minecraft?
And, try to upgrade your driver - it could just be a driver bug.

**Comment by Gh0st-VX** [comment]
According to the windows 10 driver updater, I have the latest device driver. Then again, it is an Intel q45/q43, so is heavily outdated, unsupported, and really does need replacing. Minecraft 1.12 doesn't have the super secret settings, but shaders are applied whenever you possess a creeper, spider or enderman in spectator mode, and these work fine.

Sorry I can't be of use.

**Comment by Abastro** [comment]
Hm, then it could be a shader issue. Still, it's odd that there's no log.
Please try again with this: It will still crash, it could provide more information:
https://www.dropbox.com/s/0houx1dkpk7z3wj/Stellar%20Sky-1.12.2-0.5.2.8.jar?dl=0

**Comment by Gh0st-VX** [comment]
Sorry for the slow replies, but as expected, it crashed.

Crash log:
[crash-2018-02-03_18.21.35-client.txt](https://github.com/Abastro/StellarSky/files/1692048/crash-2018-02-03_18.21.35-client.txt)

Multi-MC log:
https://paste.ee/p/yeaBU

**Comment by Abastro** [comment]
So it's not the first shader, which is the most complex one. Whew, that's a relief.
I'm really sorry for asking for too much things, but it was not enough to diagnose the problem.
Please, Would you try one more time? I really want to resolve this problem.
https://www.dropbox.com/s/0houx1dkpk7z3wj/Stellar%20Sky-1.12.2-0.5.2.8.jar?dl=0
I only need the log.

**Comment by Gh0st-VX** [comment]
I guess the most complex shader working is a good thing.

Multi-MC log:
https://paste.ee/p/keLFC

Crash log:
[crash-2018-02-04_08.42.21-client.txt](https://github.com/Abastro/StellarSky/files/1692616/crash-2018-02-04_08.42.21-client.txt)

**Comment by Abastro** [comment]
I can't track exactly where the problem lies. At least I'm sure that it's the driver bug.
So it could take some time...
Does this work?
https://www.dropbox.com/s/0houx1dkpk7z3wj/Stellar%20Sky-1.12.2-0.5.2.8.jar?dl=0

**Comment by Gh0st-VX** [comment]
I can confirm it crashes like before.

Multi-MC log:
https://paste.ee/p/hoDX0

Crash log:
[crash-2018-02-04_21.23.27-client.txt](https://github.com/Abastro/StellarSky/files/1693330/crash-2018-02-04_21.23.27-client.txt)

**Comment by Abastro** [comment]
Hmm... It could mean that the driver has fundamental bug... (related with point sprites)
Anyway, this will still crash but will help diagnose the problem.
https://www.dropbox.com/s/0houx1dkpk7z3wj/Stellar%20Sky-1.12.2-0.5.2.8.jar?dl=0

**Comment by Gh0st-VX** [comment]
Multi-MC log:
https://paste.ee/p/VsRla

Crash log:
[crash-2018-02-05_17.47.37-client.txt](https://github.com/Abastro/StellarSky/files/1696189/crash-2018-02-05_17.47.37-client.txt)

**Comment by Abastro** [comment]
Fortunately it seems like it's not a fundamental problem - point sprite is fine.
So... do this work? This will let me diagnose the root of the problem. (Either by working or not working)
https://www.dropbox.com/s/0houx1dkpk7z3wj/Stellar%20Sky-1.12.2-0.5.2.8.jar?dl=0

**Comment by Gh0st-VX** [comment]
Well... It doesn't crash. 

The sun looks a bit odd though.
![2018-02-07_19 28 02](https://user-images.githubusercontent.com/35869020/35937281-aa9abf68-0c3d-11e8-9829-bdb9c9a6b440.png)
![2018-02-07_19 26 32](https://user-images.githubusercontent.com/35869020/35937284-ac7af73a-0c3d-11e8-9ab4-cbe1d191c9e8.png)

In all seriousness it does look like the problem is a lot closer to being solved, as I believe you removed the troublesome shader (Which I suspect gives the day sky the light blue colour). I have included the Multi-MC log for completions sake.

Multi-MC log:
https://paste.ee/p/7iITx

**Comment by Abastro** [comment]
Sorry for late reply.
Strange... The sky should render fine. But it could be glitch from the missing shader field.
I'm kinda lost what part is working and whatnot. - This is why I'm late.
Anyway, does this work?
https://www.dropbox.com/s/0houx1dkpk7z3wj/Stellar%20Sky-1.12.2-0.5.2.8.jar?dl=0
If it doesn't, what about this?
https://www.dropbox.com/s/xh7cq5lyble6hdm/Stellar%20Sky-1.12.2-0.5.2.8.jar?dl=0

**Comment by Gh0st-VX** [comment]
The first file crashed.
Multi-MC log:
https://paste.ee/p/cnJ45

Crash log:
[crash-2018-02-10_22.36.08-client.txt](https://github.com/Abastro/StellarSky/files/1713826/crash-2018-02-10_22.36.08-client.txt)

The second file didn't crash, and had a similar effect to the images above.

**Comment by Abastro** [comment]
Well, dang. It's definitely a driver bug then. Still, I'll try to find the solution.

**Comment by Abastro** [comment]
Sorry, really can't find a solution for this. Wait for driver update.
Honestly, I can't work with drivers which does strange voodoo magic on its texture.

**Comment by Gh0st-VX** [comment]
I have a new computer, with a graphics card that works with the mod. Thanks anyways.
