### ISSUE TITLE
0.4.2.6 crashes dedicated server Forge 1.12.2 build 2607

### ISSUE THREAD

**Issue by kreezxil** [Abastro/StellarSky#94]
Notes:
     major server side crash, recurs on each start

crash report:
https://gist.github.com/cb0e13d8f7a7f881ce5a5bafd0c304bf

fml server latest:
https://gist.github.com/90d8b8b0f293bd95553ffc72acf5f0a7

**Comment by kreezxil** [comment]
Ok, I updated to the latest release and got the same thing, I think this is forge related.

It apparently didn't start until I updated into Forge build 2601

1.12.2-0.5.2.6 crashes dedicated server Forge 1.12.2 build 2607

Notes:
     same as above

crash report:
https://gist.github.com/012ce20863bfbcc32f2dcb9a828ed2cd

fml server latest:
https://gist.github.com/ee6486211ddc68b30226742799cb574c

**Comment by Abastro** [comment]
Does this occur on the pre-existing world? Or does this also occur on the new world?
EDIT: Ah, it seems like I made a dumb mistakes related with server.

**Comment by kreezxil** [comment]
yes, when the world was upgraded to either of the two versions
