### ISSUE TITLE
[1.12.2] Crash when changing dimensions

### ISSUE THREAD

**Issue by brisingraerowing** [Abastro/StellarSky#95]
[Crash Log](https://gist.github.com/BrisingrAerowing/66fe0af5d415d802a352fd70b3a12008)

Stellar Sky: 0.5.2.7
Stellar API: 0.4.2.7

Slightly annoying.

**Comment by Abastro** [comment]
This doesn't happen only with Stellar API & Stellar Sky, so this seems like a compatibility issue. Also it's mysterious...
On what dimension does this crash happened?
And please try with this file:
https://www.dropbox.com/s/0houx1dkpk7z3wj/Stellar%20Sky-1.12.2-0.5.2.8.jar?dl=0
It will still crash, but it will help clarifying the issue.
Also, please post log. It is vital in this case to find the issue.

**Comment by brisingraerowing** [comment]
I’m not using this mod anymore (incompatible with Galacticraft), and I don’t remember what I was doing with this.
