### ISSUE TITLE
[1.12.2] The Betweenlands Compatibility

### ISSUE THREAD

**Issue by SlimF** [Abastro/StellarSky#96]
[crash-2018-02-18_21.24.19-client.txt](https://github.com/Abastro/StellarSky/files/1735060/crash-2018-02-18_21.24.19-client.txt)

[crash-2018-02-18_21.58.24-client.txt](https://github.com/Abastro/StellarSky/files/1735056/crash-2018-02-18_21.58.24-client.txt)

Every time I try to go to the Betweenlands dimension, the game crashes. The first log is from version 0.5.2.7, the second is from the version you posted here: #95

**Comment by Abastro** [comment]
To resolve this issue, a log file is needed. It should be in logs folder in the minecraft directory.

**Comment by Abastro** [comment]
Please try with Stellar API 0.4.2.8 when it comes out.

**Comment by Abastro** [comment]
Please reply, or this will be closed in a week.

**Comment by SlimF** [comment]
I am terribly sorry for my absence and no logs whatsoever. 

I just tried to enter the Betweenlands dimension with Stellar API 0.4.2.9 and Stellar sky 0.5.3.1 and it is working without any problems. Thank you very much for your work and again, sorry for my lack of help.
