### ISSUE TITLE
Crash Entering DimensionalDoors Pocket Dimension

### ISSUE THREAD

**Issue by UndeadZeratul** [Abastro/StellarSky#98]
Tried entering a Dimensional Doors pocket dimension dungeon and instantly received the "Server Shutting Down" message.

[crash report](https://pastebin.com/WJfxgnEF)

StellarAPI v1.12.2-0.4.2.7
StellarSky v1.12.2-0.5.2.7
DimensionalDoors v3.0.7-b-1.233

**Comment by Abastro** [comment]
To resolve this issue, a log file is needed. It should be in logs folder in the minecraft directory.

**Comment by UndeadZeratul** [comment]
I'll see if I can get that for you later today, if not by the end of this week.

**Comment by UndeadZeratul** [comment]
[Here's](https://gist.githubusercontent.com/UndeadZeratul/b11178f0d5500088f16e7c4cddd7f156/raw/685beade7f970606dee79920ec960c29d4d76d11/gistfile1.txt) the fml-client-latest.log from my last session where I basically flew around trying to find a dimensional doors portal and entered it.  Was this the log you were referring to?

EDIT: changed link to the full file, github gist truncates long files by default.

**Comment by Abastro** [comment]
Yes, it's the right file. But.. sorry, would you try with the latest version? It generates additional logs to investigate this issue further.

**Comment by UndeadZeratul** [comment]
Oh, sure.  I wanted to stay on that version since that's what I reported it with, but I can certainly update my pack and try again when I have the chance.

**Comment by UndeadZeratul** [comment]
[Here's](https://gist.githubusercontent.com/UndeadZeratul/6bc6b5d23f47d144a5eb7fba6758f4c5/raw/1d6d18e57f1db01cfbe04039dbb116a039a72c27/gistfile1.txt) the latest log file from my most recent attempt.  I updated Stellarsky to version v1.12.2-0.5.2.8

**Comment by NightKosh** [comment]
Hello. 
It looks like I've got a similar problem with my mod's dimension. Could you please look on it? 

Also I'd like to know is there any way to disable your mod for specific dimensions? It will be an option for me cause my dimension almost completelly filled with bedrock and havn't got sky at all.

https://github.com/NightKosh/Gravestone-mod-Extended/issues/133

**Comment by Abastro** [comment]
@NightKosh Thanks! I'm working on it, and I suspect that this is because of the overworld-like worldset applied to not-actually-overworld-like dimensions.
You can find it among the worldsets, try disabling it(I can't recall what was the name exactly)

**Comment by Abastro** [comment]
Please try with Stellar API 0.4.2.8 when it comes out.

**Comment by DnielMC** [comment]
Still crashing with 4.2.8 in Twilight Forest and Deep Dark
https://pastebin.com/KrmC9WES

**Comment by Abastro** [comment]
@DnielMC This seems to be a completely different issue. Try Stellar API 1.12.2-0.4.2.9, and if it doesn't work, repost this issue.

**Comment by DnielMC** [comment]
It's working again! :D Let's hope it doesn't break again if any of the other mods update c:

**Comment by UndeadZeratul** [comment]
Hey @Abastro sorry for the really late reply, I got caught up with some real life things and didn't get a chance to check Github in a while.

Good news is I loaded up my world with the StellarApi v4.2.9 and I popped into the Dimensional Doors dungeon that was failing to load before, so from what I can tell it looks like this has been fixed!  Thanks for fixing it!

**Comment by Abastro** [comment]
Glad this fixed it! =)
